### ISSUE TITLE
Feature Request: items per page

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#10]
Add a setting to control how many items are per page.

I'm guessing the current option is in place to keep page loads fast, but making it user-configurable would be great.

**Comment by barbequesauce** [comment]
OK - give that a whirl...

**Comment by jandreaucodes** [comment]
Now I see no movies in my Library at all.

It's like the "per page" Setting defaulted to 0, but I don't see an option in the UI to change it.

As of right now, my Library looks like this: 
![image](https://user-images.githubusercontent.com/12860371/64550899-e3b18200-d301-11e9-8bab-1296e52e19d5.png)

Toggling pages and "Hide Finished" doesn't seem to work, as if there's a .js conflict somewhere.

**Comment by barbequesauce** [comment]
Might need to flush caches again... javascript can be a real pain at times

**Comment by jandreaucodes** [comment]
No dice. I hard refreshed 10 times, tried incognito and tried Safari and Firefox (which I've never looked at Watcher in, so they have no caches)

However, in Safari if I change the page # dropdown, I get other pages with varying numbers of movies on them: https://take.ms/SOOzy

**Comment by barbequesauce** [comment]
That video was useful, thanks. I think my fix to the page counts for "Hide finished" and this are conflicting. Let me dig a little deeper.

**Comment by barbequesauce** [comment]
OK - I think I nailed it this time?

**Comment by jandreaucodes** [comment]
No dice for me. I'm still seeing the same behavior after pulling down the changes to /static/js/library/status.js

Tried a bunch of cache clearing refreshes and also Firefox and Safari.

**Comment by jandreaucodes** [comment]
I stand corrected, it looks like I had to force a rebase. It looks like it's working now, _however_ changing the per page setting is incredibly slow to redraw the page.

If I select 250 (or more) it takes about 15-20 seconds to redraw. I think that'd be fine if there was a progress spinner on the page while it loaded.

**Comment by barbequesauce** [comment]
Good suggestion... Do you have any examples of pages that have a spinner like that handy, so I can see how it works?

**Comment by jandreaucodes** [comment]
I can't think of one offhand, but I don't hate the way pyMedusa does it. There's just a little text on screen until it loads, a la:

![image](https://user-images.githubusercontent.com/12860371/64881924-01e0f000-d62a-11e9-8ee3-99cde3252735.png)

**Comment by barbequesauce** [comment]
Glowing praise :)

I'll take a look at it now

**Comment by barbequesauce** [comment]
Try that on for size...

**Comment by jandreaucodes** [comment]
Looks good to me! Thanks for the quick turnaround.
