### ISSUE TITLE
Post Processing missing Title

### ISSUE THREAD

**Issue by mels0n** [barbequesauce/Watcher3#102]
**Describe the bug**
Post Processing sometimes doesn't include title, so the show doesn't have a title on either the Library Status page, or the directory structure.

**To Reproduce**
Setup post processing to include {title}, trigger a download. 

**Expected behavior**
{title} to be replaced with the shows title.

Included logs of one movie that worked and one that didn't. Both were triggered exactly the same way. Search, then add movie - with the same settings active. In fact, taking note of the timestamps one will note they processed around 5 minutes apart.

[Didn't work.txt](https://github.com/barbequesauce/Watcher3/files/3974183/Didn.t.work.txt)
[worked.txt](https://github.com/barbequesauce/Watcher3/files/3974184/worked.txt)

![image](https://user-images.githubusercontent.com/17222454/71011904-3ac2b200-20bc-11ea-800d-cc27c9d27da4.png)

![image](https://user-images.githubusercontent.com/17222454/71011948-4dd58200-20bc-11ea-8b5c-52a7f8682692.png)

![image](https://user-images.githubusercontent.com/17222454/71012059-7fe6e400-20bc-11ea-9f86-4e7cc1fc131e.png)

**Comment by mels0n** [comment]
If it matters I had nosmokingbandit and then switched to this fork after install. I am a new user, installed yesterday for the first time.

**Comment by ellnic** [comment]
I don't get this behavior, and I use similar renaming to you. If you change it to:

`{title} ({year})`

Does it still happen?

**Comment by mels0n** [comment]
> I don't get this behavior, and I use similar renaming to you. If you change it to:
> 
> `{title} ({year})`
> 
> Does it still happen?

Interestingly I did settle on exactly this naming. It hasn't happened again, but at the same time my usage has been minimal and it was intermittent issue to start, as shown in the report.

**Comment by ellnic** [comment]
Ok, if you could continue to test with the year in brackets, then let us know if you see it at all. It's probably a bug when the 2 tags are used without anything separating them.

**Comment by ellnic** [comment]
@mels0n any more issues now you are using the brackets?

**Comment by mels0n** [comment]
I haven't been able to recreate this... I may have just had something
corrupted somehow.

**Comment by ellnic** [comment]
Do you mean that you cannot recreate with the `{title} ({year})` or you've gone back to `{title} {year}` and it hasn't reoccurred?

**Comment by mels0n** [comment]
I am using () currently, but I tested about a dozen times without and was
unable to recreate my original experience.

**Comment by ellnic** [comment]
Ok, lets close this for now - but if come across the issue again, we can reopen.
