### ISSUE TITLE
Delete Movie File toggle 

### ISSUE THREAD

**Issue by mels0n** [barbequesauce/Watcher3#103]
**Describe the bug**
Delete Movie File toggle doesn't toggle checked / doesn't work.

**To Reproduce**
1. Click Movie in Library Status
2. Click trashcan icon
3. Attempt to toggle the box to delete files as well.

**Expected behavior**
Clicking the box will put an identifier in the box to indicate it has been activated. Then the file would be deleted instead of just removing it from the library.

![image](https://user-images.githubusercontent.com/17222454/71013052-0bad4000-20be-11ea-8a39-a56020bbd101.png)

**Comment by barbequesauce** [comment]
Sounds css-like to me @ellnic :)

**Comment by ellnic** [comment]
My first thought was that I messed up the MDI update, but I have just checked and both MDI icons display correctly (the other being mdi-checkbox-marked, you can also used mdi-checkbox-checked but both are displaying correctly). This appears to be controlled by 'c_box' which is (as far as I can see nothing to do with CSS), so I moved onto JS and it seems to be controlled by this snippet of code in manage.js:

```
var c = movie.querySelector("i.c_box");
c.classList.remove("mdi-checkbox-blank-outline");
c.classList.add("mdi-checkbox-marked");
c.setAttribute("value", "True");
```

This is JS so either @barbequesauce or @scambra

I am pretty much going to be busy until after Christmas now, so Merry Christmas and Happy Holidays to all and best wishes for 2020! :)

**Comment by barbequesauce** [comment]
OK - it's on tomorrow's hotlist...

**Comment by barbequesauce** [comment]
Safari & Chrome on macOS, I can't reproduce... what OS & browser are you using?

**Comment by mels0n** [comment]
Google Chrome is up to date
Version 79.0.3945.88 (Official Build) (64-bit)

Windows 10, version 1903

**Comment by ellnic** [comment]
I'm using Firefox 71.0 (Canonical 1.0), I also see this on Chromium 79.0.3945.79 (Official Build). 

@mels0n are you using Docker?

**Comment by barbequesauce** [comment]
Blergh. Blew out caches after adding in that last PR and now I can reproduce on both Safari & Chrome on macOS.

**Comment by barbequesauce** [comment]
Interestingly, the HTML template implies that you can delete a movie... but the js says:

```
        "remove": {
            title: "Remove Movies",
            body: "Selected movies will be removed from the library.<br/>This will not delete movie files.<br/>This cannot be undone.",
            task: "_remove"
```

I'm still reading into why the js is written to not delete it...

**Comment by ellnic** [comment]
Was it possible that it was never completed?

**Comment by scambra** [comment]
checkbox is readed in _remove_movie function:

```js
    if(document.querySelector("div#delete_file > i.c_box").getAttribute("value") === "True"){
        delete_file = true;
    } else {
        delete_file = false;
    }
```

But I don't see any event changing value attribute for it, I don't if it has been removed. Some JS files have a event listener in document, so probably it would be good idea to have it in a shared js for whole watcher, instead of having it in settings/shared.js and import/shared.js, but it would require to clean up every existing listener for checkboxes, and there are other duplicated code too which may be done in a cleaner way, so I just fixed it adding a new event listener to this checkbox, and cleaning can be done later.

**Comment by barbequesauce** [comment]
I think you nailed it... I've been hacking changes to manage/remove_movie for the last hour instead of looking for listeners...

**Comment by scambra** [comment]
> Interestingly, the HTML template implies that you can delete a movie... but the js says:
> 
> ```
>         "remove": {
>             title: "Remove Movies",
>             body: "Selected movies will be removed from the library.<br/>This will not delete movie files.<br/>This cannot be undone.",
>             task: "_remove"
> ```
> 
> I'm still reading into why the js is written to not delete it...

That JS is in manage page, but this issue is in status page
