### ISSUE TITLE
Broken UI when adding movie

### ISSUE THREAD

**Issue by exenza** [barbequesauce/Watcher3#105]
**Describe the bug
When reviewing the search results for adding a movie the page is truncated and cannot scroll to the end of the page

**To Reproduce**
1. Go to Add Movie
2. Click on search bar and search or use any of the search button (popular, top rated...)
3. Scroll down to end of page
4. Last movies will be truncated

**Expected behavior**
I should be able to scroll to the end of the page and see the action buttons under the posters

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - Chrome and Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 13.3

**Additional context**
Requesting desktop version in Chrome has no effect

**Comment by barbequesauce** [comment]
Funny enough, I found this one last night too... @ellnic since it’s GUI can you please take a first stab to rule out css? I’m thinking the last set of spacing tweaks might be involved...

**Comment by ellnic** [comment]
It’s funny actually because I was seeing this issue on desktop and the last PR actually solved it. It looks as though it may have now moved to mobile. May I suggest we ask @ronilaukkarinen for input, as it may well be that the pending PR (#104 ) solves this.

**Comment by ronilaukkarinen** [comment]
I'll check this out soon!
