### ISSUE TITLE
Manage page layout changed

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#106]
Manage page used to have a movie per row, but now it's rendered with boxes and some text cannot be read. I think it wasn't intended, but it was changed with some change to status page.

**Comment by barbequesauce** [comment]
Likely related to #104 or #105 ...

**Comment by barbequesauce** [comment]
Now that #107 is merged, does this still occur for you?

**Comment by ronilaukkarinen** [comment]
Sorry! I did not realize manage and add movie use the same classes in different files. Upcoming PR fixes this. 👍

**Comment by barbequesauce** [comment]
I wish merges didn't close issues...

@scambra how does this look for you?

**Comment by ronilaukkarinen** [comment]
Oh sorry, accidentally tagged the issue without confirming. In my end everything seems to look fine with the latest master up to date.

**Comment by scambra** [comment]
They're good now
