### ISSUE TITLE
Page count is wrong when you select "Hide Finished items"

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#11]
Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: 4567311
** Operating System: MacOS 10.14.5
** Python Version [python -V]: 3.7.3
** What happened: When you select "Hide Finished items", the number of total pages is wrong. See screenshot here: https://take.ms/DN0q4

I only have 5 pages of Waiting items, so pages 6-18 should be hidden in the pagination.
** Logs:
```
Not necessary for this bug```

**Comment by barbequesauce** [comment]
Give that a try.

**Comment by jandreaucodes** [comment]
I'm up to date with this patch, but still see the number of pages being wrong.

I have 5 pages of wanted/waiting, but see 18 pages (including 13 pages of finished items).

**Comment by barbequesauce** [comment]
Might need to flush caches... also flip it to show all then reselect hide finished...

**Comment by jandreaucodes** [comment]
Looks good now. The unchecking and re-checking is what did the trick.
