### ISSUE TITLE
Watcher title search - erroneous digit parsing

### ISSUE THREAD

**Issue by enilfodne** [barbequesauce/Watcher3#112]
**Describe the bug**
When the search query is numbers only, Watcher assumes its the year and create an erroneous search query.

**To Reproduce**
1. Go to `Add Movie`
2. Enter `<digits>`. For example (`1917`, `1998`, `2001`)
3. You'll get the movie whose id (in the TheMovieDB) corresponds to `<digits>`

**Expected behavior**
The query should complete successfully

**Additional context**
The issue seems to stem from the [following](https://github.com/barbequesauce/Watcher3/blob/master/core/movieinfo.py#L90) feature, which takes the last four digits as the year (useful when looking for a movie with a common title). However it doesn't check the length or if there's a preceding space (as you would normally type `<movie-name> <year>`.

**Comment by barbequesauce** [comment]
Great writeup - your analysis seems spot-on, thanks.

We do accept PRs :)

**Comment by scambra** [comment]
Indeed it's feature to search by TMDB id, which are only digits:
https://github.com/barbequesauce/Watcher3/blob/master/core/movieinfo.py#L63

```
INFO [2020-02-05 11:10:24,792] core.movieinfo.search.59: Searching TheMovieDB for 1917
INFO [2020-02-05 11:10:24,794] core.movieinfo._search_tmdbid.153: Searching TheMovieDB for TMDB ID: 1917.
INFO [2020-02-05 11:10:24,794] core.movieinfo._search_tmdbid.157: Searching TMDB https://api.themoviedb.org/3/movie/1917?language=en-US&append_to_response=alternative_titles,external_ids,release_dates
```

However, searching by "1917 " doesn't search by TMDB id, but it searches by title, but it takes 1917 as year because search title is stripped, removing trailing blank spaces:
```
INFO [2020-02-05 11:12:59,591] core.movieinfo.search.59: Searching TheMovieDB for 1917 
INFO [2020-02-05 11:12:59,592] core.movieinfo._search_title.86: Searching TheMovieDB for title: 1917 .
INFO [2020-02-05 11:12:59,593] core.movieinfo._search_title.97: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=&year=1917
WARNING [2020-02-05 11:12:59,935] root.open.94: Error code 422 in response from https://api.themoviedb.org/3/search/movie
ERROR [2020-02-05 11:12:59,936] core.movieinfo._search_title.111: Error searching for title on TMDB.
Traceback (most recent call last):
  File "/app/watcher/core/movieinfo.py", line 107, in _search_title
    return results['results'][:6]
KeyError: 'results'
INFO [2020-02-05 11:12:59,936] core.movieinfo.search.69: Nothing found on TheMovieDatabase for 1917 
INFO [2020-02-05 11:12:59,937] core.ajax.search_tmdb.87: No Results found for 1917 
```

This workaround would work better if year is taken only when search string is longer than 4 characters. I'm not sure how to avoid searching by TMDB id in this case, workaround doesn't feel right to me. Maybe changing UI to select title, IMDB id and TMDB id instead of guessing.

**Comment by scambra** [comment]
Another way, without changing UI, it's remove guessing TMDB id, and have user to add tmdb: prefix to search string. We could require imdb: prefix too, to be consistent, or keep guessing, as imdb always start by tt. We can have tooltip explaining search is by title, and how to search by tmdb id or imdb id.

**Comment by barbequesauce** [comment]
last option is most user-friendly, I think.... how tough are the code changes? Not too bad, I wouldn't think?

**Comment by scambra** [comment]
Last option should be really easy:
Change condition in line 63 of movieinfo.py to check tmdb: prefix, and line 64 to pass search_term[5:](removing tmdb: prefix).
Change line 61 and 62 in same way if we want to use imdb: prefix too.
Add tooltip to input text in add_movie.html template

**Comment by scambra** [comment]
I have changed search by tmdbid to use tmdb: prefix in 424e9947f
Also, fixed when title are only 4 digits, so we don't search with empty term and year because it fails, so search for 1917 movie works.

I'm not sure if we want to require imdb: prefix for imdb id search, or keep current way, checking term format has imdb id pattern (tt[0-9]+), @barbequesauce @ellnic what is more user friendly?

**Comment by barbequesauce** [comment]
tt12345678 is how sickgear/sickbeard does it, if radarr & sonarr do too I would accept that as a “standardize”.

**Comment by ellnic** [comment]
I agree, standardise.

**Comment by scambra** [comment]
I don't have radarr or sonarr anymore, I don't remember how it works there. @ellnic do you agree with adding imdb: prefix too?

**Comment by ellnic** [comment]
@scambra yes, I think it would be the best approach.

**Comment by scambra** [comment]
Add movie search is looking for movies by title, and it parses year if last 4 characters are digits.
However, if search term starts with tt and everything else are digits, it looks for movie by imdb id (imdb id is ttXXXXXXX where X is a digit)
And when whole search term was a number, it was searching by tmdb id (tmdb id is a number, no alphabetic char), which prevented to find movies such as 1917. I changed to search by tmdb id when search term is tmdb:XXXX, where X are digits (blank space between : and digits is allowed).

So now searches work this way:
* tmdb: XXXXX searches by tmdb ID
* ttXXXXXX searches by imdb ID
* anything else searches by title

We could change imdb id search by this one:
* imdb: ttXXXXXX

The question is: do we want to keep searching by ttXXXXX, or do we want to require imdb: prefix to use imdb id search? If we change it, we change behaviour, but it's more consistent with tmdb: prefix. However, it isn't really necessary and I don't know how other apps do it now.

**Comment by barbequesauce** [comment]
Sickgear/Sickbeard interpret a leading tt and subsequent 7-9 numerics as an IMDB search request.

**Comment by ellnic** [comment]
Oh right, I understand now. This seems to be more a matter of tidy code. Why don’t we say require prefix to keep consistent with TMDB?

**Comment by scambra** [comment]
To me it's a matter of what is more user friendly, imdb: as we have tmdb:, or keep detecting imdb id format, as we do now and sickgear does (I don't remember what radarr or couchpotato does). I'm ok with current way.

**Comment by ellnic** [comment]
Oh right sorry. I literally only search without prefix so I get what you mean now. Is it possible to have both? Then existing users who are used to just ‘ttxxxxxxxx’ will continue to be able to do so, and users who use the tmdb prefix who may logically assume you would need to use imdb for that can also do so.

**Comment by scambra** [comment]
Yes, it would be possible search by ttXXXXX and imdb:ttXXXXX
