### ISSUE TITLE
Unable to Download Using qbittorrent 

### ISSUE THREAD

**Issue by ragman666** [barbequesauce/Watcher3#114]
**Describe the bug**
I am unable to use qbittorrent as the URL it defaults to is "localhost:myport/login"

qbittorrent doesnt publish its web UI on this page. the login page is just "localhost:myport"

**To Reproduce**
1. Go to 'settings/downloader'
2. Click on 'Torrent' and select 'qbittorrent'
3. Configure the host and port correctly
4. click test connection
5. this line appears in the logs
"lib.requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:myport/login'"

**Expected behavior**
I expect the test to succeed, i am also using Sonarr and this can connect using the same host/port details

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Same result in FF 72.0.1 and Chrome 79.0.3945.117

**Comment by devqore** [comment]
Should be fixed in f7f22d077bdcc34bdee7bc30691bef6f59b4bed4. Issue was related to the changes in qbittorrent v4.1 API (more details in [documentation](https://github.com/qbittorrent/qBittorrent/wiki#webui-related)). In short url `host:port/login` became `host:port/api/v2/auth/login` etc.
