### ISSUE TITLE
TypeError: unrepr does not recognize 'Constant'

### ISSUE THREAD

**Issue by nephaste** [barbequesauce/Watcher3#121]
**Describe the bug**
Python 3.8.1 on Qnap NAS on start CherryPy crash

TypeError: unrepr does not recognize 'Constant'

**Desktop (please complete the following information):**
 - OS: Linux x86_64

**Additional context**

cross compiled Python 3.8.1
on startup  
`
[~/watcher] # $PYTHON watcher.py --daemon --address 0.0.0.0 --port 19990
Connected to database sqlite:////share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Pyt                                           hon.", 'TypeError', ("unrepr does not recognize 'Constant'",))
[~/watcher] #

any idea on how to fix this issue ? thanks from Qnap NAS community
`

**Comment by barbequesauce** [comment]
Can you please share your redacted app.ini please? It reads as a config file error.

**Comment by nephaste** [comment]
not sure what you mean ?

you mean startup sequence ?

[Watcher3.zip](https://github.com/barbequesauce/Watcher3/files/4198953/Watcher3.zip)

**Comment by nephaste** [comment]
tried update CherryPy with a pip3 install --upgrade cherrypy ... has not effect

**Comment by nephaste** [comment]
watch3 logs only display

`INFO [2020-02-13 14:32:08,381] core.version.update_check.31: Checking for updates.
INFO [2020-02-13 14:32:08,830] core.version._update_check.265: Current local hash: 8c5798b7b4dd366c322ae3dc854b9ebf9900ad7a
INFO [2020-02-13 14:33:18,121] core.version.update_check.31: Checking for updates.
INFO [2020-02-13 14:33:18,530] core.version._update_check.265: Current local hash: 8c5798b7b4dd366c322ae3dc854b9ebf9900ad7a
INFO [2020-02-13 14:36:06,324] core.version.update_check.31: Checking for updates.
INFO [2020-02-13 14:36:06,763] core.version._update_check.265: Current local hash: 8c5798b7b4dd366c322ae3dc854b9ebf9900ad7a
`

**Comment by barbequesauce** [comment]
CherryPy is pinned and packaged - updating it on the system won't do anything.

I've no experience with QNAP, so trying to understand that startup script is making my head hurt :) If you look in the folder you've installed Watcher into, there should be a data folder; in there is an app.ini. That's the file I'm asking for.

**Comment by nephaste** [comment]
I have userdata in directory.. but no app.ini inside

i deleted contents and restart it

`[~/watcher] # $PYTHON watcher.py --daemon --address 0.0.0.0 --port 19990
Creating database file /share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/watcher.sqlite
Creating tables.
Connected to database sqlite:////share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/watcher.sqlite
## Config file not found. Creating new basic config /share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/config.cfg. Please review settings.
Clearing Mako cache.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))
`

and find command dont find it

[/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher] #
[/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher] # find . -name app.ini
[/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher] # find . -name app.ini
[/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher] # cd ..
[/share/CACHEDEV1_DATA/.qpkg/Watcher3] # find . -name app.ini
[/share/CACHEDEV1_DATA/.qpkg/Watcher3] #

**Comment by barbequesauce** [comment]
Sorry, wrong project :/ the right file is that config.cfg, but if you blew it out and are starting clean there shouldnt be much to see.

Where did you get the package from? Does the packager recognize the error or have any insight? It doesnt happen on a clean git install or in the docker image, both of which are supported here...

**Comment by nephaste** [comment]
i git cloned it from this repo

i show you

[~] # ls
bin/  docs/  etc/  include/  lib/  lib64@  libexec/  man/  sbin@  share/  ssl/  var/  watcher/  Watcher3.sh*

remove actual watcher

[~] # rm -rf watcher/

git cloning

[~] # git clone https://github.com/barbequesauce/Watcher3.git watcher
Cloning into 'watcher'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 10651 (delta 65), reused 67 (delta 31), pack-reused 10524
Receiving objects: 100% (10651/10651), 12.35 MiB | 10.67 MiB/s, done.
Resolving deltas: 100% (6955/6955), done.

git pulling

[~] # cd watcher
[~/watcher] # git pull
Already up to date.

starting ...

[~/watcher] # $PYTHON watcher.py --daemon --address 0.0.0.0 --port 19990
Creating database file /share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/watcher.sqlite
Creating tables.
Connected to database sqlite:////share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/watcher.sqlite
## Config file not found. Creating new basic config /share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/userdata/config.cfg. Please review settings.
Clearing Mako cache.
/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/core/searcher.py:76: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  backlog_movies = [i for i in movies if i['backlog'] != 1 and i['status'] is not 'Disabled' and Manage.verify(i, today=today)]
/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/hachoir/parser/misc/pdf.py:395: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise ParserError("Can't find '%s' starting at %u"
/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/core/postprocessing.py:577: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.get('imdbid') and data['imdbid'] is not 'N/A':
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))

**Comment by barbequesauce** [comment]
Sorry - I cant make heads or tails of what is happening here. I'm wondering if there is some weird mapping/overlay going on with interfaces or libraries in the virtualization layer?

**Comment by nephaste** [comment]
sure ...

[conf_app.zip](https://github.com/barbequesauce/Watcher3/files/4199202/conf_app.zip)
[userdata.zip](https://github.com/barbequesauce/Watcher3/files/4199205/userdata.zip)

does eventually some of this pip install --upgrade on my build script , can make it in trouble 

setuptools
pyopenssl
lxml
netifaces
pycrypto
pycurl
scandir
gevent
certbot

may be a side effect

**Comment by barbequesauce** [comment]
Watcher is designed to use it's lib directory over installed versions.
@scambra any ideas what the heck is going on here?

**Comment by scambra** [comment]
Is it possible related to #79? @nephaste said is running with Python 3.8.1 
I don't have too much experience with python, I don't know if there is a better way than having libraries in watcher's lib directory, or how to update a library copied into lib. In ruby we usually use Gemfile with dependency locking, so updating to new library versions is easy, and project doesn't include libraries, they are installed with a command, installing locked versions in Gemfile.lock file.

**Comment by barbequesauce** [comment]
Ohhhh yes you're right.... I didn't connect the dots. Python 3.8.1 has issues with the (quite old)  pinned version of CherryPy; backwards compatibility between our codebase and the current CherryPy is problematic. 

@nephaste your choices then are to run it under 3.7.x (maybe using pyenv) or wait until I finish working through #79, which has been cooking for weeks now and been one dependency issue after another.

**Comment by scambra** [comment]
we may have other errors in our code which don't work with 3.8:
watcher/core/searcher.py:76: SyntaxWarning: "is not" with a literal. Did you mean "!="?
backlog_movies = [i for i in movies if i['backlog'] != 1 and i['status'] is not 'Disabled' and Manage.verify(i, today=today)

**Comment by barbequesauce** [comment]
Yep, been working on CherryPy first...

**Comment by nephaste** [comment]
thanks for your help... i will give a try with python 3.7..

**Comment by nephaste** [comment]
confirmed it works seamlessly with Python 3.7.6  .. thanks to everyones
