### ISSUE TITLE
Plugins being deleted

### ISSUE THREAD

**Issue by bcamp929** [barbequesauce/Watcher3#124]
**Describe the bug**
From time to time, every couple days or so, my snatched and finished plugs are deleted. I have had to make a backup, so I can replace them whenever this happens.

**To Reproduce**
Install a plugin, wait a few days for it to be removed.

**Expected behavior**
Install plugin, and it should persist through reboots, and updates.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
I initially thought this was because i installed the plugin scripts with the watcher service running. I did it again without the service running, and restarted the service after the plugin script was in place. A couple days later it was missing. Today, the snatched one fired, but by the time the finished one was to fire, it was gone.

**Comment by barbequesauce** [comment]
There’s no code in there to delete plugins though...

**Comment by bcamp929** [comment]
Are updates overwriting them?

**Comment by barbequesauce** [comment]
They don’t on my system?

**Comment by bcamp929** [comment]
I will continue to monitor is order to provide you with more useful
information.

**Comment by scambra** [comment]
How did you install? Docker? git? Is it happenning when app is updated?

**Comment by bcamp929** [comment]
From Git, downloaded zip file. I just installed the update (that resolved
something with rarbg) and my plugins are gone again. So, i believe the
updates are wiping any plugins i have in place.

**Comment by barbequesauce** [comment]
how are you applying the zip?

**Comment by bcamp929** [comment]
Extracted and moved into /opt.

**Comment by barbequesauce** [comment]
I'm baffled. Can you show the exact commands you're issuing please?

Out of curiosity, why not use git?

**Comment by bcamp929** [comment]
Exact commands to install and run?

I honestly don't know why i chose not to use git, i usually do. It would
make sense to try that as git only updates files that have updates,
correct? I will gladly try that and see how it goes.

**Comment by barbequesauce** [comment]
Any news? feel free to reopen if you have followup news.

**Comment by bcamp929** [comment]
I apologize. I installed using GIT, and this does not seem to happen
anymore. Thanks!
