### ISSUE TITLE
Searches not happening

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#126]
**Describe the bug**
Scheduled or manual searches do not appear to be happening. No errors are logged in the error_log

**To Reproduce**
1. Select any movie in your list of Wanted films
2. Click the magnifying glass to search for it
3. Nothing happens. Normally I'd get a "No results found, trying again in 24 hours message". But here the magnifying glass stops animating and no results are found. 

Error log doesn't show any search for the movie, either.

**Expected behavior**
Either a result is found, or the error of no matches is show.

**Screenshots**
Video: https://take.ms/xKjD3

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None needed.

**Comment by barbequesauce** [comment]
What do you see when you click the (!) button next to the search button? That should show what was found but was rejected due to quality, size etc.

**Comment by jandreaucodes** [comment]
I do see results there.

Did the "No matches found" message get taken out when a manual search was run? That's what lead me to think this wasn't working (also, nothing's downloaded on its own in a while).

**Comment by barbequesauce** [comment]
"No matches found" was removed because there _were_ matches... it's just that they were rejected...

**Comment by jandreaucodes** [comment]
Ah, okay. I guess that makes sense.

So, to clarify the "i" icon is all rejected matches. If I found something that wasn't rejected, it'd show when I manually search, right?

**Comment by barbequesauce** [comment]
Exactly.
