### ISSUE TITLE
Torrent not handing off to Transmission

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#13]
Before submitting an issue...

* Enable debug logging in settings/server.

* Repeat the actions required to reproduce the error.

Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: 456731103ca682fc8fc199e0e9d2f52fd9a77f39
** Operating System: MacOS 10.14.5
** Python Version [python -V]: 3.7.3
** What happened: When I manually search for a torrent and click the download link, I get an error of "Query failed with result "download directory path is not absolute"."

I don't know where that's coming from or how to fix it. CouchPotato worked fine with Transmission, so I think it's an error in my Watcher settings, but I don't see anything around directory path in Watcher's settings.

All other downloaders I've used (CouchPotato, pyMedusa, Radarr, Sonarr) work, so I'm 99% sure I've got a setting wrong in Watcher, but damned if I can find it. I posted to Reddit, but got no response, hence filing the issue here, hoping someone can help me fix it.
** Logs:
```
DEBUG [2019-08-01 07:44:49,168] core.sqldb.get_single_search_result.601: Retrieving search result details for ff1dcdbc91413741daf7676a5c3f97da6fb9643e.
DEBUG [2019-08-01 07:44:49,168] core.sqldb.execute.156: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE guid="ff1dcdbc91413741daf7676a5c3f97da6fb9643e" ORDER BY score DESC, size DESC']
INFO [2019-08-01 07:44:49,172] core.snatcher.download.162: Sending 1408.2007.DC.1080p.BluRay.x264-SiNNERS to download client.
INFO [2019-08-01 07:44:49,173] core.snatcher.snatch_torrent.249: Sending magnet to Transmission
INFO [2019-08-01 07:44:49,173] core.downloaders.Transmission.add_torrent.49: Sending torrent 1408.2007.DC.1080p.BluRay.x264-SiNNERS to Transmission.
ERROR [2019-08-01 07:44:49,213] core.downloaders.Transmission.add_torrent.89: Unable to send torrent to TransmissionRPC.
Traceback (most recent call last):
  File "/Applications/Watcher/Watcher3/core/downloaders/Transmission.py", line 82, in add_torrent
    download = client.add_torrent(url, paused=paused, bandwidthPriority=bandwidthPriority, download_dir=download_dir, timeout=30)
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 418, in add_torrent
    return list(self._request('torrent-add', args, timeout=timeout).values())[0]
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 263, in _request
    raise TransmissionError('Query failed with result \"%s\".' % (data['result']))
transmissionrpc.error.TransmissionError: Query failed with result "download directory path is not absolute".
```

**Comment by barbequesauce** [comment]
I'm using Transmission as well with no problem. Can you share your Transmission config? What version are you using?

Do you have a label set?

**Comment by jandreaucodes** [comment]
Happy to share my config. Is there a way to export that from the GUI?

I'm on version 2.94. No label set through Watcher. Should I? What does that do? I've never labeled any torrent before.

**Comment by barbequesauce** [comment]
A screenshot from Watcher's Downloaders screen would be enough. Also, what do you have Transmission's default download directory to

I wonder if the missing label is the issue. Would you mind setting it just to see? The label field will tell Transmission to put downloads in a subdirectory of it's default download directory; the subdirectory will be named with the label name.

**Comment by jandreaucodes** [comment]
Yep, looks like the handoff works fine when the label is added.

I'll see if my external post-processing stuff works when the download completes, but at least it handed off properly with the label set now.

Making that _unrequired_ would be ideal since I don't care where they go when they're downloading, as Filebot grabs the completed file anyway and renames and moves it.

**Comment by barbequesauce** [comment]
Great. That pins down what I need to change too.

I should get to that tomorrow... stay tuned.

**Comment by barbequesauce** [comment]
Sorry, still testing this. In the meantime, can you please close your other issue?

**Comment by barbequesauce** [comment]
OK, give that a try...

**Comment by jandreaucodes** [comment]
No dice. I did a 'git pull', and seem to be up to date, but I still get a 503 error if I try to hand off to Transmission without a "label" in my Transmission settings.

**Comment by jandreaucodes** [comment]
Actually, it looks like the issue might be with certain providers throwing the 503.

It looks like this has resolved the issue for me, as long as the providers aren't erroring out.
