### ISSUE TITLE
IMdB sync not working

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#130]
**Describe the bug**
I just setup (3 days ago) a brand new watchlist on IMdB and linked it to Watcher through its setting.

According to "System", the sync is running, but none of the movies from IMdB are showing up in Watcher.

Also, there's no new Logs generating for my Watcher instance. The last log I have is from 02-29, though it contains data from the 1st. No log has been written since the 1st.

This is the watchlist I'm testing with: https://www.imdb.com/user/ur64152031/watchlist, feel free to test with it. 

**To Reproduce**
1. Add IMdB watch list to Watcher
2. Force a sync (or wait for it to happen)
3. See no movies synced

**Expected behavior**
Movies sync from IMdB to Watcher

**Screenshots**
Screenshots not applicable.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.3
 - Browser All
 - Version Latest

Semi-related note: the Trakt sync requires Trakt VIP, right? It doesn't say that in the docs, but it looks like to get the RSS feed for your list on Trakt, you need to pay for VIP.

**Comment by barbequesauce** [comment]
Traveling for work this week - I'll try it when I get home...

I'm watching Trakt popular, new, and some other public list without paying...

**Comment by barbequesauce** [comment]
> Semi-related note: the Trakt sync requires Trakt VIP, right? It doesn't say that in the docs, but it looks like to get the RSS feed for your list on Trakt, you need to pay for VIP.

Confirmed, that's a new(ish) change by Trakt.

Regarding IMDb, I'm seeing the same lack-of-synching - digging into their docs, unless you have an IMDbPro account the watchlists are not visible. Do you have one?

**Comment by jandreaucodes** [comment]
Yeah, my wife and I both have Watchlists and aren't IMdB pro.

They sync to Radarr without any issue.

My URL(if you want to use it for testing) is: https://www.imdb.com/user/ur64152031/watchlist

As long as it's set to public, I know it syncs with Radarr, so in theory it should be able to sync with Watcher3, I'd hope.

**Comment by jandreaucodes** [comment]
I just did a fresh install of Watcher3 and it looks like my first list is syncing a-okay.

Maybe it was a temporary issue on IMdB's side, but it looks to have cleared up now.

I'm going to file a feature request for an enhancement of this, though.
