### ISSUE TITLE
Download Size limit

### ISSUE THREAD

**Issue by BryceStandley** [barbequesauce/Watcher3#134]
Just wanted to suggest making a size limit on downloads. Just so when Watcher goes and searches for downloads, it can only show the downloads that are equal to less than the given size, or greater than. That way we can better manage the amount of storage used.

**Comment by jamaroney** [comment]
Isn't that option available under "Quality"?

**Comment by BS3DP** [comment]
I am a little blind and only just noticed that but its not exactly what i was suggesting. The quality tab lets you adjust the size of each type of quality but not as a blanket value over everything if that makes sense. A over all max size value would mean the user doesn't have to go though and adjust every quality accordingly and can just say nothing larger than 25gb and then it will only show finds of 25gb or less. 

The quality tab would still adjust the given sizes but within that max size of all finds i.e. if the user sets it to 0 it can use the normal quality settings but if the user says maybe 50gb max then the qualities can be automatically adjusted to allow better turning of sized finds
