### ISSUE TITLE
Preferred words are ignored

### ISSUE THREAD

**Issue by jamaroney** [barbequesauce/Watcher3#135]
I want 5.1 audio, and entered that ("5.1") into my preferred words (I have no required words). Yet when Watcher snatches a torrent/magnet, it ignores "5.1" even though the list of qualified movies it shows has one or more entries w/ that word, and usually the movie it downloads isn't 5.1.

I don't know if this is relevant, but under "Search" I have selected "Automatically grab best release".

**Comment by scambra** [comment]
Can you provide debug logs? Enable debug logs, restart, then search movie again

**Comment by jamaroney** [comment]
Sorry, that was a while ago - no logs were kept. The problem only occurred with that one particular movie, and disappeared once the movie was finally available for download

**Comment by barbequesauce** [comment]
OK - let us know when you can recreate please...
