### ISSUE TITLE
Unselected movies are being deleted

### ISSUE THREAD

**Issue by jamaroney** [barbequesauce/Watcher3#136]
This has happened three times in the last 24 hours: In "Library"->"Manage", if I select 1 movie for deletion, then several other finished movies are deleted as well. Fortunately, I have a backup, so I re-place them in the Library. But if re-do a selection delete, the same movies (3 others) are again deleted.

**Comment by barbequesauce** [comment]
What movies? Got a log?

**Comment by jamaroney** [comment]
Please disregard. I'm a noob, and my movies were getting deleted because I misunderstood some of the settings - Watcher was simply doing what I had instructed it to do!  Later today it wiped out ALL my movies - thank goodness for backups.

Just to clarify - "Directory Scanner" refers to adding a directory OTHER than the default directory that my downloader (transmission) uses, correct?

**Comment by barbequesauce** [comment]
Correct :)
