### ISSUE TITLE
Allow changing TPB indexer URL

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#138]
**Is your feature request related to a problem? Please describe.**
ThePirateBay goes up and down a lot, and depending on your ISP, it may be blocked entirely.

**Describe the solution you'd like**
Many other downloaders (Radarr, Sonarr, Headphones, etc.) allow you to specify a proxy URL for TBP.

I'd like to see Watcher3 incorporate something similar, so when the main URL goes does, I can change my index to look at a proxy instead.

**Comment by jamaroney** [comment]
You can use Jackett to handle Pirate Bay and others like a Torznab indexer.

**Comment by jandreaucodes** [comment]
> That would be handy, but you can also use Jackett to handle Pirate Bay and others like a Torznab indexer.

I hadn’t even thought of that. It’ll work but Jackett on Mac requires a ton of Mono dependencies that a lot of folks may not be on board with.

**Comment by jamaroney** [comment]
I'm a newb to Watcher (liking it a  lot!), but I agree w/ your initial suggestion. Right now, a number of the indexers' sites have changed, and I ended up converting them all to TorzNab via Jackett. This could be avoided if we could directly change the URL to proxy sites.

**Comment by barbequesauce** [comment]
Looking at the underpinnings, there's a lot of custom scraper code for each of the hardcoded torrent sites; given that, it wouldnt make sense to make them openly editable from the GUI where people could mistakenly put another tracker in the slot. I can easily move their URLs to the config file as a test if that would work?

**Comment by jamaroney** [comment]
That would be a big help!

**Comment by jandreaucodes** [comment]
I'd be happy to try that out.

**Comment by scambra** [comment]
I have added option to define url for all torrent providers and default to previous value if it's empty.

@barbequesauce @ellnic I'm not sure if UI is good, maybe is better to have one line for each indexer

**Comment by scambra** [comment]
@jandreaucodes is it pirate bay working for you? I have used new feature to use proxy for some indexers, but pirate bay is returning html with no result, I think it requires JS to send search to /newapi/q.php?q=... and it return json
