### ISSUE TITLE
downloads very different movie

### ISSUE THREAD

**Issue by jamaroney** [barbequesauce/Watcher3#141]
New documentary movie just coming out on streaming - "It Started As a Joke". Didn't expect any hits yet, but I entered it and immediately came up w/ two hits for "Come As You Are"!

One hit started to download, and I marked both as "bad", which stopped the process.

"Joke" now appears as "Wanted", but why would it match that name w/ something completely different?

**Comment by barbequesauce** [comment]
I'd expect it's a metadata issue at either IMDb or TMDB.

I see "It Started as a Joke" as IMDb ID tt9617578. Which IMDb ID do you see for "Come as you Are"?

**Comment by jamaroney** [comment]
"Come As You Are" is IMDb ID tt6722726

**Comment by barbequesauce** [comment]
Try removing both and re-adding the one you want please... looks like the TMDB record was nuked in the last two days...

**Comment by barbequesauce** [comment]
Did this recur, or was it a one-off?

**Comment by jamaroney** [comment]
It only happened that one time quite a while ago, so I guess this issue can be removed.
