### ISSUE TITLE
Scroll broken in Add Movie (iOS)

### ISSUE THREAD

**Issue by davidcm** [barbequesauce/Watcher3#142]
**Describe the bug**
When accessing the Popular, Upcoming, etc. lists in Add Movie section, only the first 4 movies listed can be reached.

**To Reproduce**
1. Go to 'Add Movie'.
2. Click on 'Popular', 'Now Playing', 'Top Rated' or 'Upcoming'.
3. Scroll down to the third row.
4. See how only the top part of the third or fourth row appears (result varies depending on screen size, orientation and browser used).

**Expected behavior**
Should be able to scroll to the end of the results.

**Smartphone:**
 - Device: iPhone 6S
 - OS: iOS 13
 - Browser: Safari, Firefox

**Comment by ellnic** [comment]
Apologies for the delay. I will get to look at this over the next few days. Hope you are all keeping safe out there!

**Comment by ellnic** [comment]
Ok, so I'm hitting a wall here. I'm not great with the spacing aspect of CSS. @ronilaukkarinen are you able to take a look at this?

**Comment by ronilaukkarinen** [comment]
Glad you summoned me as CSS is what I do best. :) I just made a quick PR, seems to work as it should.

**Comment by barbequesauce** [comment]
Thanks @ronilaukkarinen !

**Comment by ellnic** [comment]
Thanks @ronilaukkarinen :-) hope you’re keeping safe and well.

**Comment by ronilaukkarinen** [comment]
Glad to help! Yes, everyone inside here in Finland since the beginning of March. I hope you guys are safe as well.

**Comment by ronilaukkarinen** [comment]
PS. I did not actually test this on iOS since I don't own an iPhone, so as soon as you confirm it working this issue can be closed.

**Comment by barbequesauce** [comment]
All good, I see all eight movies - thanks!

**Comment by davidcm** [comment]
Hi guys. Thanks for the effort, but sadly looks like I'm still having this issue in Safari. In Firefox seems fixed though.

**Comment by ellnic** [comment]
@ronilaukkarinen yes all ok here thanks. Glad you are :-)

@davidcm iPhones (as much as I love them) are a real pig when it comes to browsers. For many MANY reasons. If it’s working in Firefox and wasn’t before, I suspect it could be a cache issue With safari. The only problem being that you can’t clear cache without also clearing history. If you don’t care about history can you try this: Settings > Safari > Clear History and Website Data. If you aren’t sure if you want to do that, you could also try chrome or opera or any other browser and see if it works there. If it works on all but safari, I highly suspect it’s loading a cached copy of the CSS. Thanks Apple, for making this easy o_O

**Comment by davidcm** [comment]
@ellnic Hah, you're right. Before posting that I rebooted the phone thinking that would clean caches, but no. Sorry about that and thanks 🙂

**Comment by ellnic** [comment]
@davidcm No worries, glad you got it sorted! :-)
