### ISSUE TITLE
Error Checking for Updates Could not get local hash

### ISSUE THREAD

**Issue by d9001089** [barbequesauce/Watcher3#149]
**Describe the bug**
after the latest update I am getting this error: 
Error Checking for Updates
Could not get local hash. Check logs for details.

**To Reproduce**
install the latest update

**Expected behavior**
No error when checking for updates

**Screenshots**
n/a

**Desktop (please complete the following information):**
 windows 10

**Additional context**
I am running watcher on QNAP QTS 4.4.2. 
Stop & Restarted service - no change
See attached log file

[log.txt](https://github.com/barbequesauce/Watcher3/files/4523714/log.txt)

**Comment by barbequesauce** [comment]
`KeyError: 'sha'` usually means either git isnt installed or the install comes from a zip file. I'm not familiar with the package you're using; I'd suggest going back to the maintainer...
