### ISSUE TITLE
Docker? :)

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#15]
AFAIK, the best current Docker image seems to be https://hub.docker.com/r/uirel/watcher/ which appears to follow (or is?) https://github.com/Poag/watcher but Poag hasn't updated in some time.

Are there plans to build Docker for this? That would be awesome :)

Edit: There's also this: https://hub.docker.com/r/hurricane/watcher3 but last commit of associated repo is last year (https://github.com/hurricanehrndz/Watcher3) and there is no information about it in the description.

**Comment by barbequesauce** [comment]
I am Jon Snow when it comes to Docker... feel free to take a shot at it!

**Comment by ellnic** [comment]
Yeah I'm kind of in the same boat. I run a few containers but I don't have experience building. I will have a play around over the next few days and see if I can make something that actually works... watch this space. :)

**Comment by ellnic** [comment]
Here you go then: https://hub.docker.com/r/ellnic/watcher3

Having only ever used images (running them) and having not actually used Docker for that long anyway, I didn't realise how easy this would be. Pull an existing image (thanks hurricane), exec into it, change the git origin, git pull, docker push with new name. I take no credit for this, I pretty much didn't do anything.

**Comment by ellnic** [comment]
Ooops, I actually fudged that last push.. it should be fixed now. :)

**Comment by barbequesauce** [comment]
NICE thank you... I’ll update the Readme tomorrow to point to this.

I’ll read through the dockerhub link too...

**Comment by barbequesauce** [comment]
<a href="https://hub.docker.com/r/barbequesauce/watcher3"><img alt="Docker Build" src="https://img.shields.io/docker/cloud/automated/barbequesauce/watcher3.svg"/></a><a href="https://hub.docker.com/r/barbequesauce/watcher3"><img alt="Docker Build" src="https://img.shields.io/docker/cloud/build/barbequesauce/watcher3.svg"/>
