### ISSUE TITLE
"0 error" on Waiting search

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#155]
**Describe the bug**
If I manually trigger a search for my "Waiting" list, I get an error of "0 Error" after a few movies get searched.

**To Reproduce**
Have a bunch of movies in the Waiting queue and trigger a search on them.

**Expected behavior**
Search completes.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Nothing appears to show up in my logs for this search, so I can't pinpoint what's causing an error. Last time I was able to track it down to a movie with a colon (:) in the title, but I don't see any titles in my Waiting list out of the norm this time.

**Comment by barbequesauce** [comment]
Do you see anything in the javascript console?

**Comment by jandreaucodes** [comment]
I can't reproduce it now, either. 

An update between when I filed this and now must have fixed it.

**Comment by jandreaucodes** [comment]
I've finally been able to replicate this.

Console error is:
`jquery.310.min.js?v=010:4 POST http://mysite.com:9090/ajax/manager_backlog_search net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK) | send | @ | jquery.310.min.js?v=010:4
-- | -- | -- | --
  | ajax | @ | jquery.310.min.js?v=010:4
  | _manager_request | @ | manage.js?v=017:167
  | _backlog_search | @ | manage.js?v=017:214
  | begin_task | @ | manage.js?v=017:209
  | onclick | @ | manage:1

`
