### ISSUE TITLE
Movies not updating from Waiting to Wanted

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#156]
**Describe the bug**
I have Watcher setup with PreDB for Availability. (I also tried Home Release).

When a movie has passed its date for release (I noticed this with The Wrong Missy and Scoob!, both of which were released last week), the movie stays in Waiting and never moves to Wanted.

**To Reproduce**
Add a sample movie, such as Scoob! to your list.
It'll show as Waited.
It should be Wanted as its release date is in the past.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Chrome

**Comment by barbequesauce** [comment]
Cant reproduce this... can you provide a log please?
