### ISSUE TITLE
Finished torrents aren't removed

### ISSUE THREAD

**Issue by jamaroney** [barbequesauce/Watcher3#157]
I use Transmission. Under "Download Clients", I have checked "Remove Finished Torrents", but finished torrents are never removed.

XigmaNAS server
FREEBSD 12.1

**Comment by barbequesauce** [comment]
I have the same issue, never really got to the bottom of it. I believe it's an ownership/file lock issue...

Is your Transmission running as the same user as Watcher? Are the files still seeding or are they stopped? Are the files on the same volume or a mounted volume? If the latter, is it a local volume or NFS/SMB?

**Comment by jamaroney** [comment]
Is your Transmission running as the same user as Watcher?
Transmission is run as user "transmission". Watcher is run as user "root".

Are the files still seeding or are they stopped?
The files are stopped, as they have reached their share ratio. Transmission marks them as "Finished". Sometime after that point, Watcher should remove it, but it doesn't.

Are the files on the same volume or a mounted volume? 
The files are on a mounted local volume.

For security reasons, I can't run Transmission as root. So, I stopped Watcher, and just restarted it with the user "transmission". I'll download another torrent and let you know what happens.

**Comment by jamaroney** [comment]
See post immediately above. I changed settings so Watcher and Transmission are run by the same user (transmission).

I downloaded a new movie, which reached its max share ratio (transmission marked it as "Finished). However, the torrent remains.

**Comment by jamaroney** [comment]
Since the new commit several days ago, this problem doesn't occur anymore.
