### ISSUE TITLE
Trakt API - import watchlist

### ISSUE THREAD

**Issue by mrlt8** [barbequesauce/Watcher3#160]
**Is your feature request related to a problem? Please describe.**
New to watcher, but unable to import my watchlist from Trakt without a vip sub.

**Describe the solution you'd like**
Integrate the [Trakt API](https://github.com/trakt/api-help) in the same way [CouchPotato](https://github.com/CouchPotato/CouchPotatoServer/blob/7c097f9726ceec26fed6689f46ade00301eb1ad0/couchpotato/core/media/movie/providers/automation/trakt/main.py) and SickBeard/[pyMedusa](https://github.com/pymedusa/Medusa/blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/trakt_checker.py) do to sync with Trakt to check and import new items.

**Describe alternatives you've considered**
A scraper that can import a user's watchlist without a vip subscription?

**Comment by barbequesauce** [comment]
Understood how this could be seen as interesting, however under the covers there are queries routing through CouchPotato's servers to achieve this goal. I have neither the funding nor the desire to see my clients' data, nevermind have access to potentially identifiable information.

Reference https://github.com/CouchPotato/CouchPotatoServer/blob/7c097f9726ceec26fed6689f46ade00301eb1ad0/couchpotato/core/media/movie/providers/automation/trakt/main.py#L41

**Comment by mrlt8** [comment]
I believe the url is only used for the oauth authentication callback and, AFAIK, all tokens stay on the users system, but trakt also offers a ["device" authentication](https://trakt.docs.apiary.io/#reference/authentication-devices) method which is what sick-[rage](https://github.com/SiCKRAGE/SiCKRAGE/blob/859f7d3e2f8cc01533676c7b75124dedeaaf26cd/sickrage/core/traktapi.py#L53)/[chill](https://github.com/SickChill/SickChill/blob/57e049eb29e606d29d4e6c8277df5f3848dc9fc0/trakt/trakt.py#L35) and other clones like [medusa](https://github.com/pymedusa/Medusa/blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/traktor/trakt.py#L70) use so that no redirect/callback url is required.

Ironically, all the sick-variants seem to be recycling the same [client_id](https://github.com/SickChill/SickChill/blob/320ce499c52f35c885d190a0a4f08908adb11b18/sickbeard/__init__.py#L661-L662) and [client_secret](https://github.com/pymedusa/Medusa/blob/fc471d206394047800fe5bd7e897c89ad89a43db/medusa/app.py#L629-L630), so I don't believe any additional resources would be necessary.
