### ISSUE TITLE
Use poetry as a python dependency management utility

### ISSUE THREAD

**Issue by seppi91** [barbequesauce/Watcher3#161]
**Is your feature request related to a problem? Please describe.**
Right now libraries are stored in a directory called /lib in the root directory. These public libraries are available at pypi and provide compatibility constraints. To ease the maintenance of this application, keeping dependencies up to date in order to provide compatibility with more recent python engines or fixing security vulnerabilities, the use of a dependency management would be favorable.

**Describe the solution you'd like**
Python Poetry is a mature and widely adpoted utility for handling these kinds of issues. For 

**Describe alternatives you've considered**
pipenv - another utility which may be considered but since poetry has been released it's more or less discontinued
simple requirements.txt - the old-fashioned way to manage dependencies in a project. While users wouldn't have to download any additional package manager like `pipenv` or `poetry` they wouldn't benefit of features like auomatic venv handling, strict dependency locking and packaging.

**Additional context**
Poetry also enables a pretty easy way to publish this application to pypi. Users can then simply install it via `pip install watcher3` and are ready to go.

I will open a Merge Request for this and will be happy to hear your thoughts on it.

**Comment by barbequesauce** [comment]
Wow, thanks for this. I've been arguing with requirements.txt in an attempt to solve #79 for the last six months.... I assume you've tested this? Any idea on min/max python versions it works with?

**Comment by barbequesauce** [comment]
I've had to reinstall bencodepy, sqlalchemy, and PTN so far. Maybe i missed something? How is this supposed to work?

**Comment by seppi91** [comment]
@barbequesauce sorry for this, something must have been gone wrong when I've tested this. Obviously there are still some references to the old /lib path.
I will try to fix this asap and report back.

**Comment by barbequesauce** [comment]
It’s entirely possible I broke it as well - don’t rule that out :) I’ve never used poetry before, didn’t know to run poetry install at the root... but even after that I’m getting prompts...

**Comment by seppi91** [comment]
I think I've fixed this now. Please give it a retry by checking out this branch https://github.com/seppi91/Watcher3/tree/feature/add-python-poetry 

As soon as it works for you we can discuss how to proceed with merging this

**Comment by barbequesauce** [comment]
```
/opt/Watcher3 $ python3 watcher.py
Connected to database sqlite:////opt/Watcher3/userdata/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "watcher.py", line 118, in <module>
    from core import config, scheduler, version
  File "/opt/Watcher3/core/scheduler.py", line 10, in <module>
    from core import searcher, postprocessing, downloaders, snatcher
  File "/opt/Watcher3/core/searcher.py", line 3, in <module>
    import PTN
ModuleNotFoundError: No module named 'PTN'
```

**Comment by barbequesauce** [comment]
you can PR against develop if you'd like - I merged your branch into it

**Comment by seppi91** [comment]
You will have to activate the previously created venv first.

 > poetry Install #creates venv and installs dependencies
 > poetry shell #activates venv
 > python watcher.py

**Comment by barbequesauce** [comment]
@ellnic you're going to want to try this branch out in the docker image, it messes with pretty core stuff

**Comment by ellnic** [comment]
Sure! It might just work, but if it doesn't it should be a case of just altering the dockerfile to pull in any missing deps.

**Comment by ellnic** [comment]
I'm just building from the dev branch now to test. The tags are:

```
dev
armhf-dev
arm64-dev
```

So for example: `docker pull ellnic/watcher3:armhf-dev`

I'll let you know what happens. :)

**Comment by ellnic** [comment]
@barbequesauce so far so good. :)

**Comment by ellnic** [comment]
It might be worth you doing the same thing in your docker hub btw so that develop changes are instant and available for testing. Then if I need to and can pull changes to my repo and play with things if they break. 

1 minute addition to your docker hub auto build settings:

![docker](https://user-images.githubusercontent.com/16370944/85591021-d3725580-b63c-11ea-9fba-76985b5ea058.png)

Just add 3 more autobuilds with the source branch as `develop`, and everything else is the same but add `-dev` on the end of the tag.

**Comment by scambra** [comment]
I think PTN should not be removed from lib, we had some changes there, PTN has not been changed in years, and some of the changes were needed to fix some parsing issues.

**Comment by scambra** [comment]
According to lib/mods.txt cheroot and transmissionrpc have some changes too.

**Comment by ellnic** [comment]
> Also, PTN could be replace with [guessit](https://github.com/guessit-io/guessit), which is still being developed.

I like the look of Guessit. One of the goals of now is to bring the code of this project up to date. If PTN is no longer being maintained and Guessit is - this is a no brainer.

**Comment by scambra** [comment]
We should create issue to change PTN with Guessit, but I think changing to poetry can be finished keeping PTN in lib, and later we can replace it with Guessit when someone has time to work on it.

**Comment by barbequesauce** [comment]
Giving up on poetry after a year of arguing with it... shifting gears back to requirements.txt

**Comment by labrys** [comment]
If you don't have specific preference for poetry i can make it pip-installable for Python 3.8+ using setuptools pretty easily.

**Comment by scambra** [comment]
I don't know anything about poetry or other ways to manage dependencies on python, I just learned python so I could fix some bugs on some python software, or helping improving Watcher3. IMHO, anything would be better than having a copy of the libs, although there are some libs which were patched, so they should be kept in libs, unless the change has been merged upstream or it isn't needed with the newest version.

**Comment by barbequesauce** [comment]
I'm running the unbundled version for the last 12h or so, no issues with unpatched libs so far...

**Comment by scambra** [comment]
Using old PTN probably won't break, but the changes on PTN were made to match results better, so we should keep it, it hasn't been updated for years, so there is no reason to unvendored it.

Changes on cheroot or transmissionrpc may be bug fixes which are already fixed in newer versions, or may affect to some features, so we should check what was changed, and check if it's needed, or what we can do to use the newer version without patching it.

**Comment by barbequesauce** [comment]
@labrys can you check the PTN tweaks please?
