### ISSUE TITLE
Unable to update Kodi.

### ISSUE THREAD

**Issue by GTunney** [barbequesauce/Watcher3#168]
I've just installed Watcher3 on my QNAP NAS via OneCDOnly's sherpa.sh package.

All working good so far but one element I can't seem to get working is the update kodi library update.

If i browse manually i can hit the kodi json. But Watcher reports the below.

Any suggestions would be welcome?

```INFO [2020-08-13 20:19:59,543] core.ajax.get_log_text.569: Dumping log file log.txt to text.
WARNING [2020-08-13 20:19:38,174] core.plugins.execute.267: Kodi Library Update.py - Execution failed. Exit code 1.
INFO [2020-08-13 20:19:38,174] core.plugins.execute.263: Kodi Library Update.py - b'<urlopen error [Errno -2] Name or service not known>'
INFO [2020-08-13 20:19:37,807] core.postprocessing.default.233: #################################
```

**Comment by barbequesauce** [comment]
Two things come to mind - first, what version of python are you using? We're having trouble with some versions and dependencies... second, what's the URL for your Kodi instance? I don't use the functionality personally but I can check the code to make sure your URL matches what the code is expecting for a format...

**Comment by GTunney** [comment]
> Two things come to mind - first, what version of python are you using? We're having trouble with some versions and dependencies... second, what's the URL for your Kodi instance? I don't use the functionality personally but I can check the code to make sure your URL matches what the code is expecting for a format...

Hi,

I’m on python 3.7.4 and I’ve just put my LAN IP in for Kodi, also tried localhost as they’re both on the same box but same issue.

**Comment by barbequesauce** [comment]
you have both the address and the port set in the config?

**Comment by GTunney** [comment]
> you have both the address and the port set in the config?

Yes both IP and port

**Comment by GTunney** [comment]
Hi,

Anymore suggestions on this?

**Comment by scambra** [comment]
@GTunney check arguments in line "Executing plugin Kodi Library Update.py" in the log, it's the last part of the line, enclosed with {}, check if address and port are right. Can you test connection to that address and port from QNAP NAS? For example with "telnet address port" or "nc -zv address port"

**Comment by GTunney** [comment]
I'm not sure I follow what exactly you'd like, yes I can connect to the address and port from my NAS, all my other programs are able to call and update Kodi (SickChill, Headphones, Couchpotato).

**Comment by scambra** [comment]
If you enable debug in watcher, and restart, you should get a line like this in your log:
DEBUG [2020-09-22 15:35:00,607] core.plugins.execute.250: Executing plugin Kodi Library Update.py as ['/usr/bin/python3', '/config/plugins/finished/Kodi Library Update.py', 'Movie Title', 'Movie Year', 'IMDB ID', 'Source', 'Rated', 'source_path (from torrent)', 'target_path (after moved)', 'download id', 'finished date', 'quality', '{"address": "Kodi Address", "port": Kodi Port, "username": "Kodi User", "password": "Kodi Password", "map_from": "path in watcher", "map_to": "path in kodi}'].

This part should match with plugin settings:
{"address": "Kodi Address", "port": Kodi Port, "username": "Kodi User", "password": "Kodi Password", "map_from": "path in watcher", "map_to": "path in kodi}

If you are not using username for kodi, double check username is empty, if there is any whitespace it will try to use url with user and password. Also, you can double check settings in plugins/finished/Kodi Library Update.conf

**Comment by GTunney** [comment]
`WARNING [2020-09-24 11:07:01,839] core.plugins.execute.267: Kodi Library Update.py - Execution failed. Exit code 1.
INFO [2020-09-24 11:07:01,838] core.plugins.execute.263: Kodi Library Update.py - b"ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package"
INFO [2020-09-24 11:07:01,838] core.plugins.execute.263: Kodi Library Update.py - b' import email.utils'
INFO [2020-09-24 11:07:01,838] core.plugins.execute.263: Kodi Library Update.py - b' File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/lib/python3.7/smtplib.py", line 47, in <module>'
INFO [2020-09-24 11:07:01,838] core.plugins.execute.263: Kodi Library Update.py - b' import smtplib'
INFO [2020-09-24 11:07:01,837] core.plugins.execute.263: Kodi Library Update.py - b' File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/plugins/finished/email.py", line 6, in <module>'
INFO [2020-09-24 11:07:01,837] core.plugins.execute.263: Kodi Library Update.py - b' import email'
INFO [2020-09-24 11:07:01,837] core.plugins.execute.263: Kodi Library Update.py - b' File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/lib/python3.7/urllib/request.py", line 86, in <module>'
INFO [2020-09-24 11:07:01,837] core.plugins.execute.263: Kodi Library Update.py - b' import urllib.request'
INFO [2020-09-24 11:07:01,836] core.plugins.execute.263: Kodi Library Update.py - b' File "/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/plugins/finished/Kodi Library Update.py", line 8, in <module>'
INFO [2020-09-24 11:07:01,836] core.plugins.execute.263: Kodi Library Update.py - b'Traceback (most recent call last):'
DEBUG [2020-09-24 11:06:59,291] core.plugins.execute.250: Executing plugin Kodi Library Update.py as ['/share/CACHEDEV1_DATA/.qpkg/Watcher3/bin/python3', '/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/plugins/finished/Kodi Library Update.py', 'Hard Kill', '2020', 'tt11656172', 'WebDL-1080P', 'None', '/share/Download/Movies/Hard.Kill.1080p.WEB-DL.DD5.1.H.264-EVO-xpost/Hard.Kill.1080p.WEB-DL.DD5.1.H.264-EVO-xpost.mkv', '/share/Multimedia/Videos/Movies/Hard Kill (2020)/Hard Kill (2020).mkv', 'SABnzbd_nzo_s8giqaf2', '2020-09-24', 'Default', '{"address": "192.168.0.2", "port": 5003, "username": "gtunney", "password": "XXXXXX", "map_from": "/share/Multimedia/Videos/Movies/", "map_to": "nfs://192.168.0.2/Multimedia/Videos/Movies/"}'].
INFO [2020-09-24 11:06:59,271] core.postprocessing.default.233: #################################`

**Comment by scambra** [comment]
Did you add code for email notify plugin from #169 to Kodi Library Update.py? Kodi Library Update.py does't need email package. You should create new files for email notify plugin, so they run independently

Anyway, you got different error, but you can see args got by plugin:
"address": "192.168.0.2", "port": 5003, "username": "gtunney", "password": "XXXXXX"

If they are right, I don't know why watcher fails but other software have access. You could try with curl:
curl -s -u gtunney http://192.168.0.2:5003/jsonrpc

**Comment by GTunney** [comment]
> Did you add code for email notify plugin from #169 to Kodi Library Update.py? Kodi Library Update.py does't need email package. You should create new files for email notify plugin, so they run independently
> 
> Anyway, you got different error, but you can see args got by plugin:
> "address": "192.168.0.2", "port": 5003, "username": "gtunney", "password": "XXXXXX"
> 
> If they are right, I don't know why watcher fails but other software have access. You could try with curl:
> curl -s -u gtunney http://192.168.0.2:5003/jsonrpc

No i've not touched the kodi update source code at all, what ever its doing by referring to email is watcher doing that.

**Comment by scambra** [comment]
I see, kodi plugin loads request package, which request email package but it failed to find it because of email.py plugin is hiding email package, rename it as I said in #169 will fix this issue, but I guess you will still get urlopen error

**Comment by GTunney** [comment]
Yup back to urlopen error.

curl works fina via ssh and returns results.

**Comment by scambra** [comment]
I don't know what else to try, it's working for me although I don't have user and password in kodi

**Comment by GTunney** [comment]
> I don't know what else to try, it's working for me although I don't have user and password in kodi

Yup it's the username and password for me, I've just removed them and it looks like it's worked fine. Watcher doesn't like a username and password by the looks of it. My password doesn't have any special characters either so not sure what it can be.

`INFO [2020-09-25 07:12:32,815] core.plugins.execute.265: Kodi Library Update.py - Execution finished. Exit code 0.
INFO [2020-09-25 07:12:32,815] core.plugins.execute.263: Kodi Library Update.py - b'KODI Response: "OK"'
DEBUG [2020-09-25 07:12:30,478] core.plugins.execute.250: Executing plugin Kodi Library Update.py as ['/share/CACHEDEV1_DATA/.qpkg/Watcher3/bin/python3', '/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher/plugins/finished/Kodi Library Update.py', 'Peninsula', '2020', 'tt8850222', 'WebDL-1080P', 'None', '/share/Download/Movies/Train To Busan 2 Peninsula 2020 1080p WEB-DL H264 AC3-EVO-xpost/Train.To.Busan.2.Peninsula.2020.1080p.WEB-DL.H264.AC3-EVO-xpost.mkv', '/share/Multimedia/Videos/Movies/Peninsula (2020)/Peninsula (2020).mkv', 'SABnzbd_nzo_kjyuxglc', '2020-09-25', 'Default', '{"address": "192.168.0.2", "port": 5003, "username": "", "password": "", "map_from": "/share/Multimedia/Videos/Movies/", "map_to": "nfs://192.168.0.2/Multimedia/Videos/Movies/"}'].
INFO [2020-09-25 07:12:30,414] core.postprocessing.default.233: #################################`

**Comment by scambra** [comment]
I have fixed code for connecting kodi with authentication, you can update it and try again

**Comment by GTunney** [comment]
Winner Winner, Chicken Dinner.

All working now after those changes and with authentication
