### ISSUE TITLE
[Feature] Add subtitles download as part of the post-processing

### ISSUE THREAD

**Issue by dhiaayachi** [barbequesauce/Watcher3#172]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to download subtitles  for my movies without using 3rd party software

**Describe the solution you'd like**
I would like to have subtitle download as part of the post processing. We can also consider using https://github.com/Diaoul/subliminal to avoid having to take care of the providers.

**Describe alternatives you've considered**
Using 3rd party software, I run Bazarr but it work only with Radarr for movies. Also I can run a 3rd party script to do that.

**Additional context**
Other software that fulfill the same purpose as Watcher3 have the same feature. I like Watcher3 and I would like to have that feature added. I can also consider contributing the feature with minimal help.

**Comment by scambra** [comment]
I think it could be done with a plugin which calls subliminal script, although plugin would only try to download subtitle once. I'm using nzbToMedia script with transmission, and it uses subliminal after watcher is notified and it's enough most of the time.

If you know basic programming, you could give a look at existing plugins in https://github.com/barbequesauce/watcherplugins, probably it's easy to write.

**Comment by barbequesauce** [comment]
Submit a PR to https://github.com/barbequesauce/watcherplugins

**Comment by dhiaayachi** [comment]
Thank you will do, case closed
