### ISSUE TITLE
Fork still active? 

### ISSUE THREAD

**Issue by OneCDOnly** [barbequesauce/Watcher3#173]
@barbequesauce is this fork still being maintained? 

Cheers. 👍🏽

**Comment by jee-r** [comment]
The last commit dates back to 13 July 2020, so I would say yes.

https://github.com/barbequesauce/Watcher3/commits/master

**Comment by barbequesauce** [comment]
Yep - but as it says in the readme, help is gladly accepted.

My focus right now is unbundling the dependencies and upgrading the cherrypi version; there's plenty of other things that could use attention distinct from that effort.

**Comment by OneCDOnly** [comment]
No worries, thank you. 👍
