### ISSUE TITLE
API for renaming a folder

### ISSUE THREAD

**Issue by davidcm** [barbequesauce/Watcher3#178]
I made a plugin that, on finish, fetches some info like genre and user ratings. I'm putting this info as part of the name of the folder where the movie lives, so I can see it easily on the client. Of course, that leads to the library to lose track of that movie.

I think a good solution for that would be to have an api call in watcher that renames a directory, but also updates the database with the change.

Another option could be to have a new category of plugin, which would be called on postprocessing, and renaming could be overriden or extended... without affecting the normal course of events afterwards.

**Comment by scambra** [comment]
I think we could add an api method to update finished file for a movie, plugin has imdbid and it will know finished file for the movie

**Comment by scambra** [comment]
I have added update_movie_file api method, it requires imdbid and file params. It only updates finished_file with value in file param.

Finished plugin will get finished_file attribute in 8th arg, and imdbid in 4th arg.

For example, a plugin like this would replace pattern with replacement, and change DB with API:

Rename.py
```python
#!/usr/bin/env/python3

import sys
import os
import re
import json
import requests

script, title, year, imdbid, resolution, rated, original_file, new_file_location, downloadid, finished_date, quality, conf_json = sys.argv
conf = json.loads(conf_json)
apikey = conf['apikey']

path = re.sub(r'pattern', 'replacement', new_file_location, flags=re.IGNORECASE)
if new_file_location != path:
    url = u'http://{}:{}/api?apikey={}&mode=update_movie_file&imdbid={}&file={}'.format('127.0.0.1', 9090, apikey, imdbid, path)
    try:
        response = requests.get(url)
        if response.status_code == requests.codes.ok:
            response = response.json()
            if response['response']:
                os.rename(new_file_location, path)
                print('Renamed {} to {}'.format(new_file_location, path))
            else:
                print('API response: {}'.format(response['error']))
                sys.exit(1)
        else:
            print('API HTTP status: {}'.format(response.status_code))
            sys.exit(1)
    except Exception as e:
        print(str(e))
        sys.exit(1)

sys.exit(0)
```

Rename.conf
```json
{
  "Config Version": 2,
  "apikey": {
    "display": 0,
    "type": "string",
    "label": "API Key",
    "helptext": "",
    "value": ""
  }
}
```

**Comment by davidcm** [comment]
Thanks for speed and quality :) works perfectly.
