### ISSUE TITLE
PreDB is not finding many movies

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#179]
I saw I have many movies in Waiting status for long time, and I checked dates and few of them are old. I have verify set to PreDB, so I tried manually in predb.me, and I could find them, but category was Unknown. I have tried changing cats=movies to cats=movies,unknown and it worked. @barbequesauce @ellnic what do you think about changing predb search to movies and unknown categories? Is it good idea or do I add a setting for it? I have no much experience with predb.me

**Comment by barbequesauce** [comment]
I'd make it a switch, honestly - predb's accuracy has been good historically but less so recently...
