### ISSUE TITLE
Allow selection of multiple post-processing destination folders when adding movie

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#18]
As far I can see, Watcher only allows one post processing destination. 

This doesn't work well if you have a setup such as:

/Media/Kids Movies
/Media/Movies

This is done in case there are meta data issues and some ratings are not picked up by Emby/Jellyfin/Plex. Kids are only allowed to view films in the Kids folder as an added layer of 'rating' protection.

Watcher only has one post processing target folder. So I have been using this:

/Media/Watcher

As a catchall, then I move them out manually later to the correct folders, which does dampen some of the automagic.

I believe Radarr allowed you to select a destination folder in a drop down when adding (at the same time as you choose a quality). A default option for auto adds would also be useful.

**Comment by barbequesauce** [comment]
This is a big change, many modules need to change for this. Anyone out there want to take a crack at it?

**Comment by scambra** [comment]
I'm starting to work on this.

I intend to add it as couchpotato, with categories. New categories would be added in settings, and they will have a destination directory. Adding a movie will require to select quality and category, default category will have default destination. Also, category may have additional filters (preferred words, ignored words, required words).

Also, I would like to allow filter library by category, something which is not possible with couchpotato.

**Comment by barbequesauce** [comment]
Fantastic, thank you!

**Comment by ellnic** [comment]
This is great - thank you. Watcher really needs this.

**Comment by scambra** [comment]
It should be done

**Comment by barbequesauce** [comment]
Great work here - thank you!

**Comment by ellnic** [comment]
Awesome - thanks! :)
