### ISSUE TITLE
will not start on a fresh ubuntu 20

### ISSUE THREAD

**Issue by dgiffen** [barbequesauce/Watcher3#180]
**Describe the bug**

**To Reproduce**
i had this working on a ubuntu 18.04 system, but when i tried it on a new ubuntu 20 install it fails at start up. I had to use port 9095 on the original 18.04, have tried other ports and same everytime. On 18 it works perfectly. Great idea though. Thank you so much for all your effort. I really like the ability to use multiple folders. 

python3 /opt/watchergit/Watcher3/watcher.py --address 0.0.0.0 --port 9095
WARNING:root:Unable to set locale. Date parsing may not work correctly.
 Unable to set locale. Date parsing may not work correctly.
Connected to database sqlite:////opt/watchergit/Watcher3/userdata/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
/opt/watchergit/Watcher3/core/searcher.py:72: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  backlog_movies = [i for i in movies if i['backlog'] != 1 and i['status'] is not 'Disabled' and Manage.verify(i, today=today)]
/opt/watchergit/Watcher3/lib/hachoir/parser/misc/pdf.py:395: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise ParserError("Can't find '%s' starting at %u"
/opt/watchergit/Watcher3/core/postprocessing.py:594: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.get('imdbid') and data['imdbid'] is not 'N/A':
DEBUG:core.version:Setting updater to Git.
DEBUG:core.version:Retreiving local commit hash.
DEBUG:core.version:Executing Git command: ['git', 'rev-parse', 'HEAD']
INFO:core.version:Checking for updates.
DEBUG:core.version:Checking Git execution permission.
DEBUG:core.version:Executing Git command: ['git', 'version']
DEBUG:core.version:Fetching latest Git info.
DEBUG:core.version:Executing Git command: ['git', 'fetch']
INFO:core.version:Current local hash: 5001397edf962bc7320ebfc7a79a4d1eb23c667d
DEBUG:core.version:Retreiving commit hash history.
DEBUG:core.version:Executing Git command: ['git', 'rev-list', '@{u}']
DEBUG:core.version:1 updates are available -- latest commit: 0a574c9738b55cb71b4bdf57ba51a4398b9aa9a9.
INFO:core.version:Update found:
INFO:core.version:{'status': 'behind', 'behind_count': 1, 'local_hash': '5001397edf962bc7320ebfc7a79a4d1eb23c667d', 'new_hash': '0a574c9738b55cb71b4bdf57ba51a4398b9aa9a9'}
INFO:core.notification:Adding notification to queue.
DEBUG:core.notification:{'title': '1 Update Available <br/>', 'message': 'Click <a onclick="_start_update(event)"><u>here</u></a> to update now.<br/> Click <a href="https://github.com/barbequesauce/watcher3/compare/5001397edf962bc7320ebfc7a79a4d1eb23c667d...0a574c9738b55cb71b4bdf57ba51a4398b9aa9a9" target="_blank" rel="noopener"><u>here</u></a> to view changes.', 'type': 'update'}
INFO:core.version:Currently 1 commits behind. Automatic install disabled
Traceback (most recent call last):
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/watchergit/Watcher3/watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/opt/watchergit/Watcher3/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/opt/watchergit/Watcher3/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/opt/watchergit/Watcher3/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/opt/watchergit/Watcher3/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))

**Comment by barbequesauce** [comment]
What does `python -V` return? Or `pip freeze`?

**Comment by dgiffen** [comment]
on the ubuntu 20 machine it is Python 3.8.5
the ubuntu 18 machine is Python 3.6.9
I am going to guess this is where the issue lies, I tried updating that
cherrypi to a newer version, but that did not work.
Thanks for the speed reply, I have to kludge through remote mapping as this
ubuntu 18 is just a chromebox without any storage, so I was trying to run
this on my main media box. Of course I will settle for working.
Doug

**Comment by barbequesauce** [comment]
Yeah we are pinned to an ancient version of cherrypy unfortunately - there are a sea of dependency-breaks that we are dealing with.

If you install a pyenv environment with <3.7 you should be okay... it's a hack, but it will work.

**Comment by dgiffen** [comment]
Thanks so much for the speedy reply. I assumed that its a giant pain,
keeping all systems aligned. I appreciate the advice on the pyenv. I read
its probably the best way to go anyway. Hack or not. I'm just to lazy to
read up on it. I may just keep it on the little box and remote map
everything.
Is it within the possible here to be able to designate an IMDB list to a
specific category, or I am I just to dense to see how to do so.
Thanks
Doug

Thanks
Doug

**Comment by xoniq** [comment]
For future people, I came here because I updated to 20.04 LTS (Ubuntu) and encountered the same issue. To install `python3.7`:

1. Add PPA:
`sudo add-apt-repository ppa:deadsnakes/ppa`
2. Install `python3.7`:
  `sudo apt install python3.7`
3. Start Watcher:
  `python3.7 ~/Watcher3/watcher.py -p #### -d`
