### ISSUE TITLE
Watcher thinks it's up to date but it's not.

### ISSUE THREAD

**Issue by GTunney** [barbequesauce/Watcher3#181]
Watcher keeps thinking it is already up to date when it does an update check.

As you can see from the debug below during a version check watchers version is currently commit 013bbd which is from the 28th September 2020. But at the end of the update check it says "Watcher is up to date" when it's not. Only way I can get watcher to update is to manually ssh and do a git pull.

```
DEBUG [2020-10-13 14:24:16,771] core.version._update_check.282: Watcher is up to date.
DEBUG [2020-10-13 14:24:16,728] core.version.runner.95: Executing Git command: ['git', 'rev-list', '@{u}']
DEBUG [2020-10-13 14:24:16,728] core.version.get_commit_hash_history.140: Retreiving commit hash history.
INFO [2020-10-13 14:24:16,727] core.version._update_check.265: Current local hash: 013bbd2918e3c3723a58d5eecef5b3d84aeb2a44
DEBUG [2020-10-13 14:24:16,653] core.version.runner.95: Executing Git command: ['git', 'fetch']
DEBUG [2020-10-13 14:24:16,652] core.version.fetch.163: Fetching latest Git info.
DEBUG [2020-10-13 14:24:16,644] core.version.runner.95: Executing Git command: ['git', 'version']
DEBUG [2020-10-13 14:24:16,644] core.version.available.151: Checking Git execution permission.
INFO [2020-10-13 14:24:16,644] core.version.update_check.31: Checking for updates.
```

**Comment by barbequesauce** [comment]
What happens when you issue `git status` from the root directory of your installation?

**Comment by GTunney** [comment]
`On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   plugins/added/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        plugins/added/InstanceSync.conf
        plugins/added/InstanceSync.py
        plugins/added/InstanceSync/

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by barbequesauce** [comment]
I saw in the emailed ticket response there was an uncommitted change - I assume that was cleaned up, if you're now getting a clean status message?

That would be the only thing I can think of that would cause the behavior described above. I'll push a tiny change now for you to test the auto update feature against...

**Comment by GTunney** [comment]
> I saw in the emailed ticket response there was an uncommitted change - I assume that was cleaned up, if you're now getting a clean status message?
> 
> That would be the only thing I can think of that would cause the behavior described above. I'll push a tiny change now for you to test the auto update feature against...

Yeah it was a blank .gitignore file in one of the add on folders. Populated and its now got a clean git status but still refuses to update and thinks it is the latest version.

**Comment by barbequesauce** [comment]
Hmmm

Can we try a reset?

`git reset --hard ; git pull`

**Comment by GTunney** [comment]
> Hmmm
> 
> Can we try a reset?
> 
> `git reset --hard ; git pull`

Ok. git reset has done and completed without errors, now on latest 2b2e946. Can you commit a small change again so I can test?

**Comment by barbequesauce** [comment]
Go for it!

**Comment by GTunney** [comment]
> Go for it!

Still doesn't like it.

```
INFO [2020-10-14 09:49:32,530] core.ajax.get_log_text.565: Dumping log file log.txt to text.
DEBUG [2020-10-14 09:49:27,734] core.version._update_check.282: Watcher is up to date.
DEBUG [2020-10-14 09:49:27,691] core.version.runner.95: Executing Git command: ['git', 'rev-list', '@{u}']
DEBUG [2020-10-14 09:49:27,691] core.version.get_commit_hash_history.140: Retreiving commit hash history.
INFO [2020-10-14 09:49:27,690] core.version._update_check.265: Current local hash: 2b2e946b2a5d8c7914fea98fa26a32cc638f88a5
DEBUG [2020-10-14 09:49:27,619] core.version.runner.95: Executing Git command: ['git', 'fetch']
DEBUG [2020-10-14 09:49:27,619] core.version.fetch.163: Fetching latest Git info.
DEBUG [2020-10-14 09:49:27,609] core.version.runner.95: Executing Git command: ['git', 'version']
DEBUG [2020-10-14 09:49:27,564] core.version.available.151: Checking Git execution permission.
INFO [2020-10-14 09:49:27,564] core.version.update_check.31: Checking for updates.
```

**Comment by GTunney** [comment]
git status also thinks it's up to date but if I was to do a git pull i've no doubt it'd update.

```
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by GTunney** [comment]
I don't know much about git but readme.md is in the main gitignore list so not sure if it should show any updates after modifying that.

**Comment by barbequesauce** [comment]
I forgot we’d moved it to gitignore - just tweaked watcher.py, give that a try

**Comment by GTunney** [comment]
> I forgot we’d moved it to gitignore - just tweaked watcher.py, give that a try

No worries man, git status still thinks its already up to date. Got me baffled.

```
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

```
