### ISSUE TITLE
IMDB Will not sync

### ISSUE THREAD

**Issue by dgiffen** [barbequesauce/Watcher3#184]
I cannot get my imdb link to import. https://www.imdb.com/list/ls083812974/export 
When I click the link, I get WATCHLIST.csv, I have added slashes to the end, WATCHLIST.csv also. It then complains its not a valid list. I have a Ubuntu 20.04 server and am running watcher in a pyenv, thanks to BBQ sauce for the tip on doing this. I copy and paste the link as provided at IMDB under export this list. 

WARNING [2020-10-28 17:23:08,811] core.rss.imdb.sync.61: Unable to sync list ls083812974
WARNING [2020-10-28 17:23:08,809] root.open.94: Error code 403 in response from https://www.imdb.com/list/ls083812974/export
INFO [2020-10-28 17:23:08,563] core.rss.imdb.sync.39: Syncing rss IMDB watchlist ls083812974
INFO [2020-10-28 17:23:08,553] CPTaskScheduler._task.248: == Executing Task: IMDB Sync Per User Command ==
INFO [2020-10-28 17:23:08,553] core.ajax.manual_task_execute.1464: Manually executing task IMDB Sync.

**Comment by PrzemekSkw** [comment]
I also can't sync watchlist from IMDB. I go to IMDB> Watchlist> click share> copy link> go to Watcher>Settings>Search>Watchlist section> paste link to IMDB watchlist url field. Set ` Sync IMDB Watchlists Every [X] Minutes` to 15 minutes.
I see in log:
```
INFO [2020-12-12 21:27:49,676] core.ajax.get_log_text.565: Dumping log file log.txt to text.
INFO [2020-12-12 21:27:44,763] core.ajax.get_log_text.565: Dumping log file log.txt to text.
INFO [2020-12-12 21:27:36,465] CPTaskScheduler._task.275: == Finished Scheduled Task: PostProcessing Scan ==
KeyError: 'imdbid'
if Manage.markedresults(data['guid'], 'Bad', imdbid=data['imdbid']):
File "/home/lusia/Watcher3/core/postprocessing.py", line 393, in failed
response = self.failed(data)
File "/home/lusia/Watcher3/core/postprocessing.py", line 196, in default
pp.default(**d)
File "/home/lusia/Watcher3/core/scheduler.py", line 139, in scan_directory
self.task()
File "/home/lusia/Watcher3/lib/cherrypyscheduler.py", line 264, in _task
Traceback (most recent call last):
WARNING [2020-12-12 21:27:36,455] CPTaskScheduler._task.266: Scheduled Task PostProcessing Scan Failed:
WARNING [2020-12-12 21:27:36,455] core.library.searchresults.1012: Movie metadata not supplied, unable to create SEARCHRESULTS entry.
INFO [2020-12-12 21:27:36,455] core.library.searchresults.1010: Guid postprocessing8c27cd95c072de5cb6b42d8a3a523cb7 not found in SEARCHRESULTS, attempting to create entry.
INFO [2020-12-12 21:27:36,455] core.library.searchresults.997: Marking guid postprocessing8c27cd95c072de5cb6b42d8a3a523cb7 as Bad.
INFO [2020-12-12 21:27:36,455] core.postprocessing.failed.384: Marking guid as Bad.
WARNING [2020-12-12 21:27:36,454] core.postprocessing.default.195: Post-processing as Failed.
INFO [2020-12-12 21:27:36,454] core.postprocessing.get_movie_info.347: Unable to find local data for release. Using only data found from file.
INFO [2020-12-12 21:27:36,454] core.postprocessing.get_movie_info.329: Unable to find local release info by release name.
INFO [2020-12-12 21:27:36,453] core.postprocessing.get_movie_info.324: Unable to find local release info by release name, trying fuzzy search.
INFO [2020-12-12 21:27:36,453] core.postprocessing.get_movie_info.319: Searching local database for release name Pets...
```
Regards,
Przemek

**Comment by barbequesauce** [comment]
> WARNING [2020-10-28 17:23:08,809] root.open.94: Error code 403 in response from https://www.imdb.com/list/ls083812974/export

Error 403 is "access to the requested resource is forbidden"... that's coming from IMDb, not much we can do about that...

**Comment by PrzemekSkw** [comment]
@barbequesauce I use Couchpotato and there's no problem with IMDB watchlist. I just add my list url and it works. 
Regards.
