### ISSUE TITLE
How do I configure the timezone?

### ISSUE THREAD

**Issue by sokulski** [barbequesauce/Watcher3#187]
I see user Settings > System that the default time zone is +0. Is it possible to configure that, either as an environment variable or in the UI?

**Comment by barbequesauce** [comment]
Are you referring to this?

<img width="464" alt="Screen Shot 2020-11-22 at 8 09 07 PM" src="https://user-images.githubusercontent.com/25070944/99922455-a8308700-2cfe-11eb-8993-3990c5848e01.png">


If so, this comes from the OS...

**Comment by sokulski** [comment]
Yep, that's exactly where I'm looking.

Do you mean that it comes from the host OS? Or the OS inside the container?

**Comment by barbequesauce** [comment]
Honestly not sure as I run on bare metal, not containered... maybe @ellnic has a thought here?

**Comment by ellnic** [comment]
Good point. 

By default, the time zone inside the container should be UTC. I never really thought too much about it tbh, but you've highlighted something that can be improved.

I will need to modify the build files so that the 'TZ' variable can be passed. 

I am out most of today, but I will do it tomorrow or Friday. :-)

**Comment by sokulski** [comment]
That's awesome. Thanks to you both for your super fast responses with these images.

Let me know if you need the need environment variable tested.

**Comment by ellnic** [comment]
@sokulski Sorry I'm running a bit behind. I haven't forgotten. New aim is by end of weekend.

**Comment by ellnic** [comment]
@sokulski What is your preferred architecture?

**Comment by sokulski** [comment]
I’m running Watcher on a 32-but ARM board. ODROID HC2z

**Comment by ellnic** [comment]
Ok great. So you'll be using `armhf`

I am just waiting in the queue for the builds to start, but once finished can you please pull `ellnic/watcher3:armhf` and test a new config with the env variable `TZ` so for example:

`docker pull ellnic/watcher3:armhf`

then:

```
docker run -d \
  --name=watcher3-tztest \
  -v /path/to/DIFFERENT_TEST_CONFIG/:/config \
  -e UMASK_SET=022 \
  -e APP_UID=1000 -e APP_GID=1000 \
  -e TZ="Europe/London"  \
  -p 9090:9090 \
  ellnic/watcher3:armhf
```
Where `Europe/London` is, obviously your timezone as set by the tz database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

and then look at the system info and tell me if that's done it :)

I'll edit this when the build has completed.

**Comment by ellnic** [comment]
I just set to `Europe/Kiev` and I see this:

![time](https://user-images.githubusercontent.com/16370944/100537982-c594b200-3224-11eb-81ff-4865cddaf699.png)
