### ISSUE TITLE
Trakt sync doesn't seem to work

### ISSUE THREAD

**Issue by whi-tw** [barbequesauce/Watcher3#191]
**Describe the bug**
I'm trying to sync a watchlist rss from trakt to watcher. Adding a new movie to the watchlist does not end up in it being added to watcher.

**To Reproduce**
1. add an item to trakt watchlist
2. force trakt sync
3. nothing happens

**Expected behavior**
I would expect the item to be added to watcher

**Version**
I'm using the latest docker build as-per today. 

**Additional context**

reading `trakt.py`  it doesn't seem to do anything unless the time the rss feed was last updated is after the last sync time. I have confirmed that my timezones are all correct, and still nothing is added correctly.

```xml
  <updated>2020-12-28T16:07:08Z</updated>
```

```log
INFO [2020-12-28 16:07:18,207] CPTaskScheduler._task.248: == Executing Task: Trakt Sync Per User Command ==
INFO [2020-12-28 16:07:18,208] core.trakt.sync.30: Syncing Trakt lists.
INFO [2020-12-28 16:07:18,210] core.trakt.sync_rss.83: Syncing Trakt RSS watchlist watchlist. Last sync: 2020-12-28 16:02:32
INFO [2020-12-28 16:07:18,747] core.trakt.sync_rss.129: Storing last synced date.
INFO [2020-12-28 16:07:18,797] core.trakt.sync_rss.135: Trakt RSS sync complete.
INFO [2020-12-28 16:07:18,801] core.trakt.sync.50: Found 0 new movies from Trakt lists.
INFO [2020-12-28 16:07:18,831] CPTaskScheduler._task.273: == Finished Task: Trakt Sync ==
```

**Comment by barbequesauce** [comment]
I'm sorry, I havent been able to reproduce this. I get a half-dozen new movies a day from my collected/popular/anticipated/trending/watched feeds.

Would you be willing to share your watchlist URL?

**Comment by barbequesauce** [comment]
Please reopen if still an issue
