### ISSUE TITLE
"0 Error" on searching backlog, sometimes.

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#196]
**Describe the bug**
When running a backlog search, an error of "0 error" pops up periodically.

**To Reproduce**
1. Go to Library -> Manage
2. Click on Attribute -> Waiting
3. Run a search 

**Expected behavior**
Backlog search runs for all Waiting movies

**Desktop (please complete the following information):**
 - OS: All (but on macOS now)
 - Browser: Chrome
 - Version: 88.0.4

**Smartphone (please complete the following information):**

**Additional context**
Console error logs:
`jquery.310.min.js?v=010:4 POST http://mysite.com:9090/ajax/manager_backlog_search net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

**Comment by barbequesauce** [comment]
Assuming you get the lines:

`Performing bulk backlog search for {} movies.`

and 

`Performing backlog search for`

in your logs... what's the last one of the second one, so I can attempt to reproduce?

**Comment by jandreaucodes** [comment]
I don't see anything in my logs pertaining to that right now.

I just ran a backlog search for Waiting again, and as soon as it failed, I downloaded the logs.

What I see in the logs doesn't make sense.
The error was at 09:32:30 local time.
The last timestamp in my logs is 2021-03-10 06:13:48,251

Even if the hours were off due to timezones, the minutes are offer by half an hour. Which doesn't make sense.

I do see `Performing backlog search for` from 2 days ago. The last error there is: ```INFO [2021-03-08 17:09:33,156] core.searcher.search_all.76: Performing backlog search for tick, tick...Boom! N/A.
INFO [2021-03-08 17:09:33,156] core.searcher.search.117: Performing backlog search for tick, tick...Boom! N/A.
INFO [2021-03-08 17:09:33,157] core.providers.torrent_modules.rarbg.search.59: Performing backlog search on Rarbg for tt8721424.
INFO [2021-03-08 17:09:33,414] core.providers.torrent_modules.rarbg.search.83: Nothing found on Rarbg
INFO [2021-03-08 17:09:33,415] root.search.21: Performing backlog search on ThePirateBay for tt8721424.
INFO [2021-03-08 17:09:36,276] root._parse.67: Parsing ThePirateBay results.
ERROR [2021-03-08 17:09:36,277] root.search.38: ThePirateBay search failed.
Traceback (most recent call last):
  File "/Applications/Watcher3/core/providers/torrent_modules/thepiratebay.py", line 32, in search
    return _parse(response, imdbid)
  File "/Applications/Watcher3/core/providers/torrent_modules/thepiratebay.py", line 70, in _parse
    rows = json.loads(response)
  File "/Users/Alfred/.pyenv/versions/3.6.12/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/Alfred/.pyenv/versions/3.6.12/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Alfred/.pyenv/versions/3.6.12/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO [2021-03-08 17:09:36,278] core.providers.torrent_modules.yts.search.22: Performing backlog search on YTS for tt8721424.
INFO [2021-03-08 17:09:37,106] core.searcher.remove_inactive.286: Filtering releases based on enabled newznab indexers.
INFO [2021-03-08 17:09:37,108] core.searchresults.score.37: No releases to score.
INFO [2021-03-08 17:09:37,111] core.searcher.store_results.322: 0 results found for tt8721424. Storing results.
INFO [2021-03-08 17:09:37,112] core.searcher.store_results.332: Storing backlog search results -- purging existing results before writing to database.
INFO [2021-03-08 17:09:37,141] core.library.movie_status.1085: Determining appropriate status for movie tt8721424.
INFO [2021-03-08 17:09:37,178] core.library.verify.878: tick, tick...Boom! passes verification checks, will include title in search.```

**Comment by barbequesauce** [comment]
That traceback indicates a bad or empty response from TPB... and the search queue is dying after. Do you have other providers enabled?

**Comment by jandreaucodes** [comment]
Yes. I have YTS, Rarbg, and 6 through Jackett

**Comment by barbequesauce** [comment]
Maybe try again without TPB? Restart as well and make sure the log is getting updated correctly...

**Comment by jandreaucodes** [comment]
It seems to be getting stuck at 22/345 now. I cancel and rerun and the same thing happens.

It must be one of the movies in my Wanted section, but I can't find what from the logs.
