### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by neo-neo1** [barbequesauce/Watcher3#201]
Is this project still active? As a current Medusa user and old time CoachPotato lover i just heard about this project hoping to install. But I see no releases for 7 months and not a single reply to any issues posts? Is this project worth the Docker pull and configuration time? I generally prefer Python3 projects over the mainstream *arr apps. 

Is this abandonware? Yet another dead fork of a dead fork? Seems the answer is obvious but I hope to be wrong. 

is there anyone out there?

**Comment by barbequesauce** [comment]
I'm still here, been tinkering on the cherrypy/python upgrade for months unsuccessfully. As the trader says, it's largely meant to be a contrib-based repo - I'm using it as a learning project and can't make big changes (yet).
