### ISSUE TITLE
Add extra script after post processing option

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#23]
Again, this is like Sickgear and is not the same as watcher post processing via download client as shown here: https://github.com/nosmokingbandit/watcher/wiki/Post-Processing#scripts

Sickgear's post processing settings page refers to this as: Extra scripts - scripts are called after built-in post processing

I find this extremely useful to run a permissions correction and tidy up.

**Comment by barbequesauce** [comment]
Yeah, I think you're right. I'll put that on the to-do list for later today.

**Comment by barbequesauce** [comment]
plugins repo forked and you're both added as contributors. Thanks!
