### ISSUE TITLE
Problem with Movie Titles with Apostrophe or Colon

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#33]
I am having trouble downloading movies that have  ‘ (Apostrophe) or : (Colon) in the title of the movie. If I uncheck Score and filter release titles in the Settings -> Quality section then the movie will be downloaded. But when I have that unchecked sometimes Watcher downloads the wrong movie.  Here’s what happens when Watcher sees a movie with an apostrophe in a movie title.

INFO [2019-09-19 03:58:58,050] core.searcher.rss_sync.210: Parsing RSS for The President's Analyst 1967
INFO [2019-09-19 03:58:58,054] core.searcher.rss_sync.235: Found 1 new results for The President's Analyst 1967.
INFO [2019-09-19 03:58:58,054] core.searcher.get_source.340: Determining source media for The.Presidents.Analyst.1967.DVDRip.x264-HANDJOB
INFO [2019-09-19 03:58:58,055] core.searcher.get_source.359: Source media determined as DVD-SD
INFO [2019-09-19 03:58:58,055] core.searchresults.score.38: Scoring 1 releases.
INFO [2019-09-19 03:58:58,058] core.searchresults.remove_ignored.133: Filtering Ignored Words.
INFO [2019-09-19 03:58:58,058] core.searchresults.remove_ignored.147: Keeping 1 releases.
INFO [2019-09-19 03:58:58,058] core.searchresults.keep_required.168: Filtering Required Words.
INFO [2019-09-19 03:58:58,059] core.searchresults.keep_required.182: Keeping 1 releases.
INFO [2019-09-19 03:58:58,059] core.searchresults.retention_check.200: Checking retention [threshold = 3811 days].
INFO [2019-09-19 03:58:58,060] core.searchresults.retention_check.213: Keeping 1 releases.
INFO [2019-09-19 03:58:58,060] core.searchresults.score_sources.399: Filtering resolution and size requirements.
INFO [2019-09-19 03:58:58,061] core.searchresults.score_sources.436: Keeping 1 releases.
INFO [2019-09-19 03:58:58,061] core.searchresults.fuzzy_title.312: Checking title match.
INFO [2019-09-19 03:58:58,061] core.searchresults.fuzzy_title.349: Keeping 0 releases.
INFO [2019-09-19 03:58:58,062] core.searchresults.score_preferred.280: Scoring Preferred Words.
INFO [2019-09-19 03:58:58,062] core.searchresults.score.101: Finished scoring releases.
INFO [2019-09-19 03:58:58,062] core.searcher.rss_sync.244: No acceptable results found for tt0062153

**Comment by barbequesauce** [comment]
I got Child's Play snatched after applying this fix, so I think it's addressed - give it a spin.

**Comment by weekender23** [comment]
Thanks.  I was able to snatch The President's Analyst.
