### ISSUE TITLE
Bug: Count of pages wrong when hiding finished movies

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#35]
** Commit:2568ca29e358d47da4d48b059708a19621f56383
** Operating System: macOS
** Python Version [python -V]:3+

Issue: When using items per page, the count of number of pages is wrong. See: 
![image](https://user-images.githubusercontent.com/12860371/65353310-ce1e4100-dbba-11e9-9e80-e56e6ad484a4.png)

It seems to calculate the number of pages based on the total of all movies, not excluding finished movies.

**Comment by barbequesauce** [comment]
Argh sorry

**Comment by barbequesauce** [comment]
Condition to reproduce: if HF is flipped from true to false, all subsequent per-page value changes change screen layout but do not impact the pages count. Flipping back to true eliminates for that library render; resetting to false returns to error condition.

**Comment by barbequesauce** [comment]
#57 fixed this in a cleaner way.

**Comment by scambra** [comment]
I don't see any other weird issue with paging
