### ISSUE TITLE
When searching Watcher won't keep releases

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#39]
I think I found a bug. For some reason watcher thinks that the Source media for this movie is DVD-1080p and DVD-720p. When you go into Setting->Quality->Sources there is no Source called DVD-720p or DVD-1080p.  So watcher does not keep the releases.

INFO [2019-09-23 10:48:59,417] core.searcher.remove_inactive.271: Filtering releases based on enabled newznab indexers.
INFO [2019-09-23 10:48:59,417] core.searcher.get_source.340: Determining source media for The.Great.Santini.1979.720p.HDTV.x264-BREEVE
INFO [2019-09-23 10:48:59,418] core.searcher.get_source.359: Source media determined as DVD-720P
INFO [2019-09-23 10:48:59,418] core.searcher.get_source.340: Determining source media for The.Great.Santini.1979.1080p.AMZN.WEB-DL.DDP2.0.x264-ABM
INFO [2019-09-23 10:48:59,419] core.searcher.get_source.359: Source media determined as DVD-1080P
INFO [2019-09-23 10:48:59,419] core.searcher.get_source.340: Determining source media for The.Great.Santini.1979.1080p.AMZN.WEBRip.DDP2.0.x264-ABM
INFO [2019-09-23 10:48:59,419] core.searcher.get_source.359: Source media determined as DVD-1080P
INFO [2019-09-23 10:48:59,420] core.searcher.get_source.340: Determining source media for The.Great.Santini.1979.1080p.AMZN.WEB-DL.DD2.0.X264-ABM
INFO [2019-09-23 10:48:59,420] core.searcher.get_source.359: Source media determined as DVD-1080P
INFO [2019-09-23 10:48:59,420] core.searcher.get_source.340: Determining source media for The.Great.Santini.1979.1080p.AMZN.WEB-DL.DD2.0.X264-ABM
INFO [2019-09-23 10:48:59,421] core.searcher.get_source.359: Source media determined as DVD-1080P
INFO [2019-09-23 10:48:59,421] core.searchresults.score.38: Scoring 5 releases.
INFO [2019-09-23 10:48:59,424] core.searchresults.remove_ignored.133: Filtering Ignored Words.
INFO [2019-09-23 10:48:59,424] core.searchresults.remove_ignored.147: Keeping 5 releases.
INFO [2019-09-23 10:48:59,425] core.searchresults.retention_check.200: Checking retention [threshold = 3811 days].
INFO [2019-09-23 10:48:59,425] core.searchresults.retention_check.213: Keeping 5 releases.
INFO [2019-09-23 10:48:59,426] core.searchresults.score_sources.403: Filtering resolution and size requirements.
INFO [2019-09-23 10:48:59,426] core.searchresults.score_sources.440: Keeping 0 releases.
INFO [2019-09-23 10:48:59,427] core.searchresults.score.101: Finished scoring releases.
INFO [2019-09-23 10:48:59,451] core.searcher.store_results.307: 0 results found for tt0079239. Storing results.
INFO [2019-09-23 10:48:59,452] core.searcher.store_results.317: Storing backlog search results -- purging existing results before writing to database.
INFO [2019-09-23 10:48:59,457] core.library.movie_status.1016: Determining appropriate status for movie tt0079239.
INFO [2019-09-23 10:48:59,464] core.library.verify.812: The Great Santini passes verification checks, will include title in search.
INFO [2019-09-23 10:48:59,464] core.library.movie_status.1053: Setting MOVIES tt0079239 status to Wanted.

**Comment by barbequesauce** [comment]
I don't see that quality in the code or in the config file. Did you create your own sources in the config? 

Alternately it might be some Aliases magic. If the answer to the above question is no, can you post a copy of your config.cfg with all API keys, passwords etc redacted?

**Comment by weekender23** [comment]
here is my config file.

[config.cfg.zip](https://github.com/barbequesauce/Watcher3/files/3643927/config.cfg.zip)

**Comment by barbequesauce** [comment]
For the life of me, I can't see where it's finding DVD-1080P. Anyone else willing to chime in on this?

**Comment by scambra** [comment]
In config I can see empty string as DVD alias, also for webdl and webrip. So empty string is always matched in scene data. Empty string should be removed from aliases, when saving or reading, I guess.

Also, there is nothing in the code which prevents to return DVD-1080p, if torrent name is tagged like that. It may be probably good, because it would be rejected, torrent is very probably a fake because it doesn't make sense to have such resolution from DVD.

**Comment by barbequesauce** [comment]
Closed for inactivity. Feel free to reopen if the last comment doesnt help.
