### ISSUE TITLE
Watcher won't Push Movies to Nzbget

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#41]
Hi

For some reason watcher won't push any movies automatically to nzbget. I have to go into watcher and click  the movie and then the  download button. After that, the movie will get pushed to nzbget and download.

[log.txt](https://github.com/barbequesauce/Watcher3/files/3678706/log.txt)

**Comment by barbequesauce** [comment]
What do you have the options on the Search settings screen set to? Many of those will delay automatic release selection and download...

**Comment by weekender23** [comment]
Here's a screen shot of what my settings are in Search.

![image](https://user-images.githubusercontent.com/33842064/66009169-29c7b480-e46e-11e9-966c-829ee0e76bb6.png)

**Comment by barbequesauce** [comment]
Nothing standing out from that. Debug logs please?

**Comment by weekender23** [comment]
For debug logs do i  go into  Settings->Server-> and check off Debug Logging?

**Comment by barbequesauce** [comment]
Yes.

**Comment by weekender23** [comment]
Here is my debug Logs.
[Debug_log.txt](https://github.com/barbequesauce/Watcher3/files/3687140/Debug_log.txt)

**Comment by barbequesauce** [comment]
The search keeps crashing when looking for "22 July" - bad data in either IMDB or TMDB. Try removing it and then re-adding it...

**Comment by weekender23** [comment]
so i deleted "22 July" movie from watcher.  The movies will now push to nzbget when i use "Add Movies" in watcher. But if add movies in my IMDB wish list watcher will find the movie and add it, but will not push the movie to nzbget.   These are the movies that were found by watcher but did not get pushed to nzbget.

The Ninth Gate 
Maiden 
Child's Play

[Debug_log.txt](https://github.com/barbequesauce/Watcher3/files/3691852/Debug_log.txt)

**Comment by weekender23** [comment]
You can close this.  I figured out what was wrong.

**Comment by barbequesauce** [comment]
What was it?

**Comment by weekender23** [comment]
There was a movie (can't remember the exact name, something Treasure and the year had N/A in it) that watcher kept on giving errors in the logs.  Once i deleted that movie, the other movies began to push to NZBget.  I don't know if it matters but the Year of the movie was N/A, so i ended up deleting any movies that had N/A in the title. So far it's working.
