### ISSUE TITLE
Downloader settings should hide options for non-selected programs

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#42]
It's hard to find where are settings for your nzb or transmission program, so all settings should be hidden except settings related to selected program

**Comment by barbequesauce** [comment]
Eh? This isn’t very clear... mockups?

**Comment by scambra** [comment]
Screenshots for current downloader settings, for torrent there are more options displayed, but they doesn't fit in screen:
![image](https://user-images.githubusercontent.com/20515/66120875-2c481c80-e5dc-11e9-8c7d-598f49be92b5.png)
![image](https://user-images.githubusercontent.com/20515/66120899-3d912900-e5dc-11e9-89fb-72f66ab7d38f.png)

I would like to have this:
![image](https://user-images.githubusercontent.com/20515/66121006-77fac600-e5dc-11e9-91ad-fb1d25a21583.png)

I was going to hide groups manually, but I saw data-enabled attribute. This CSS rule hide non-selected groups:
```css
div[data-enabled=False] {
    display: none;
}
```

However, changing torrent downloader to Qbittorrent didn't hide transmission settings and show qbittorrent settings, data-enabled attribute didn't change, although I see JS is changing max-height, but 0% doesn't work, if I change to 0 it works. Also, transition doesn't work with max-height: 100%, but it would work for max-height: 1000px. Anyway, I think it's better to use data-enabled attribute in javascript and add CSS based on data-enabled instead of setting inline style with JS.

**Comment by barbequesauce** [comment]
NICE! I'll review the PRs shortly.

**Comment by barbequesauce** [comment]
Merged! Thank you!
