### ISSUE TITLE
Have postprocessing rename before move

### ISSUE THREAD

**Issue by ridizy** [barbequesauce/Watcher3#56]
I believe when both `Rename Movies` and `Move Movies` are selected in Postprocessing, Watcher moves the movie file to its final destination with its original name first, then renames it. 

In my instance, Plex sees the file system change and adds the movie to the library with the original name which is often obfuscated. It then sees the renamed movie a few moments later and adds it to the library again, but this time with its proper name. I end up with a bad entry in my library that I have to manually cleanup. I know I can set Plex to automatically `Empty trash` regularly, but there are other reasons why I don’t like to leave this enabled. 

Would it make sense to change the order of operations to do the rename before the move?  Or to do the move into the new file name?

**Comment by barbequesauce** [comment]
You're correct, that is how it works.

Renaming before moving/copying will break one important use case - where the original file is kept intact for seeding purposes.

Renaming is an atomic transaction separate from a copy/move to avoid issues when traversing file systems.

The scenario you're describing is exactly why there is a [Plex plugin](https://github.com/nosmokingbandit/watcherplugins/tree/master/finished/Plex%20API%20Scan); best practice is to disable automatic library scan and to use the plugin to trigger the scan once post-processing is complete. See more details [here](https://github.com/nosmokingbandit/Watcher3/wiki/Plugins).

**Comment by ridizy** [comment]
Thanks, I was trying to think of workflows that changing the order might break and hadn't considered those that use torrents.  Although in the case of a move, I would think the seeding would potentially break anyway.

Either way, thanks for looking into this and suggesting a workaround.
