### ISSUE TITLE
Post processing failure

### ISSUE THREAD

**Issue by Obscurax** [barbequesauce/Watcher3#59]
** Commit: https://github.com/barbequesauce/Watcher3/commit/73e9275e7eb492c0bb9a5a636c6df11b761a0130
** Operating System: Server 2019
** Python Version [python -V]: python-3.7.4-amd64
** What happened: Post processing fails
** Logs:
```
INFO [2019-10-14 12:37:39,281] core.postprocessing.default.156: #################################
INFO [2019-10-14 12:37:39,281] core.postprocessing.default.157: Post-processing request received.
INFO [2019-10-14 12:37:39,281] core.postprocessing.default.158: #################################
INFO [2019-10-14 12:37:39,281] core.postprocessing.get_movie_file.240: Finding movie file.
INFO [2019-10-14 12:37:39,328] core.postprocessing.get_movie_file.266: Largest file in directory \\kratos\dump\Watcher\Midsommar.2019.1080p.BluRay.x264-GECKOS is \82413d4e609640068d28ed837c697c87.mkv, processing this file.
INFO [2019-10-14 12:37:39,328] core.postprocessing.default.190: Gathering release information.
INFO [2019-10-14 12:37:39,328] core.postprocessing.get_movie_info.288: Searching local database for guid.
INFO [2019-10-14 12:37:39,328] core.postprocessing.get_movie_info.291: Local release info found by guid.
INFO [2019-10-14 12:37:39,328] core.postprocessing.get_movie_info.326: Searching local database by imdbid.
INFO [2019-10-14 12:37:39,328] core.postprocessing.get_movie_info.329: Movie data found locally by imdbid.
INFO [2019-10-14 12:37:39,328] core.library.from_file.396: Gathering metadata for \\kratos\dump\Watcher\Midsommar.2019.1080p.BluRay.x264-GECKOS\82413d4e609640068d28ed837c697c87.mkv.
INFO [2019-10-14 12:37:39,328] core.library.parse_filename.521: Parsing directory name for movie information: Midsommar.2019.1080p.BluRay.x264-GECKOS.
INFO [2019-10-14 12:37:39,328] core.library.parse_filename.529: Found {'year': 2019, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'group': 'GECKOS', 'title': 'Midsommar', 'release_name': 'Midsommar.2019.1080p.BluRay.x264-GECKOS'} in filename.
ERROR [2019-10-14 12:37:39,328] cherrypy.error.2685719431368.error.219: [14/Oct/2019:12:37:39] HTTP 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 191, in default
    data.update(self.get_movie_info(data))
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 343, in get_movie_info
    mdata = Metadata.from_file(data['original_file'], imdbid=data.get('imdbid'))
  File "C:\Program Files (x86)\Watcher\core\library.py", line 414, in from_file
    titledata = Metadata.parse_filename(filepath)
  File "C:\Program Files (x86)\Watcher\core\library.py", line 548, in parse_filename
    meta_data['category'] = Metadata.get_category_from_path(filepath)
  File "C:\Program Files (x86)\Watcher\core\library.py", line 564, in get_category_from_path
    if moverpath and re.match(Metadata.root_mover_path(moverpath), filepath):
  File "C:\Python37\lib\re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "C:\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Python37\lib\sre_parse.py", line 493, in _parse
    sourceget()
  File "C:\Python37\lib\sre_parse.py", line 256, in get
    self.__next()
  File "C:\Python37\lib\sre_parse.py", line 246, in __next
    self.string, len(self.string) - 1) from None
re.error: bad escape (end of pattern) at position 14
INFO [2019-10-14 12:37:39,344] cherrypy.error.2685719431368.error.219: [14/Oct/2019:12:37:39] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: identity
  HOST: 127.0.0.1:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 273
```

**Comment by barbequesauce** [comment]
That's.... odd. What's mover path set to in your config.cfg file?

**Comment by Obscurax** [comment]
![afbeelding](https://user-images.githubusercontent.com/6681453/66842495-a927ae80-ef6b-11e9-96f5-cbab585ba36e.png)

**Comment by barbequesauce** [comment]
that's an interesting rename pattern (and I suspect the source of the issue)... why parent_dir instead of title? Are you looking to retain the release group etc?

**Comment by barbequesauce** [comment]
Best guess is that it's choking on backslashes for some reason - I don't see an obvious gotcha in the code.

Would you be averse to changing the rename pattern to release_name? It should accomplish the same goal you're aiming for without tripping over os path separators...

**Comment by Obscurax** [comment]
Postprocessing is still failing after changing the rename pattern.

![afbeelding](https://user-images.githubusercontent.com/6681453/66896288-d10f2480-eff4-11e9-862d-2e87efe38c43.png)

`INFO [2019-10-16 09:08:40,987] core.postprocessing.default.156: #################################
INFO [2019-10-16 09:08:40,987] core.postprocessing.default.157: Post-processing request received.
INFO [2019-10-16 09:08:40,987] core.postprocessing.default.158: #################################
INFO [2019-10-16 09:08:40,987] core.postprocessing.get_movie_file.240: Finding movie file.
INFO [2019-10-16 09:08:41,034] core.postprocessing.get_movie_file.266: Largest file in directory \\kratos\dump\Watcher\Fast.And.Furious.Presents.Hobbs.And.Shaw.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG is \db7534fae4794bdbafea8a963109ea47.mkv, processing this file.
INFO [2019-10-16 09:08:41,034] core.postprocessing.default.190: Gathering release information.
INFO [2019-10-16 09:08:41,034] core.postprocessing.get_movie_info.288: Searching local database for guid.
INFO [2019-10-16 09:08:41,034] core.postprocessing.get_movie_info.291: Local release info found by guid.
INFO [2019-10-16 09:08:41,034] core.postprocessing.get_movie_info.326: Searching local database by imdbid.
INFO [2019-10-16 09:08:41,034] core.postprocessing.get_movie_info.329: Movie data found locally by imdbid.
INFO [2019-10-16 09:08:41,034] core.library.from_file.396: Gathering metadata for \\kratos\dump\Watcher\Fast.And.Furious.Presents.Hobbs.And.Shaw.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG\db7534fae4794bdbafea8a963109ea47.mkv.
INFO [2019-10-16 09:08:41,034] core.library.parse_filename.521: Parsing directory name for movie information: Fast.And.Furious.Presents.Hobbs.And.Shaw.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.
INFO [2019-10-16 09:08:41,034] core.library.parse_filename.529: Found {'year': 2019, 'resolution': '1080p', 'quality': 'WEB-DL', 'codec': 'H.264', 'group': 'NTG', 'title': 'Fast And Furious Presents Hobbs And Shaw', 'release_name': 'Fast.And.Furious.Presents.Hobbs.And.Shaw.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG'} in filename.
ERROR [2019-10-16 09:08:41,034] cherrypy.error.2410687568264.error.219: [16/Oct/2019:09:08:41] HTTP 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 191, in default
    data.update(self.get_movie_info(data))
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 343, in get_movie_info
    mdata = Metadata.from_file(data['original_file'], imdbid=data.get('imdbid'))
  File "C:\Program Files (x86)\Watcher\core\library.py", line 414, in from_file
    titledata = Metadata.parse_filename(filepath)
  File "C:\Program Files (x86)\Watcher\core\library.py", line 548, in parse_filename
    meta_data['category'] = Metadata.get_category_from_path(filepath)
  File "C:\Program Files (x86)\Watcher\core\library.py", line 564, in get_category_from_path
    if moverpath and re.match(Metadata.root_mover_path(moverpath), filepath):
  File "C:\Python37\lib\re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "C:\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Python37\lib\sre_parse.py", line 493, in _parse
    sourceget()
  File "C:\Python37\lib\sre_parse.py", line 256, in get
    self.__next()
  File "C:\Python37\lib\sre_parse.py", line 246, in __next
    self.string, len(self.string) - 1) from None
re.error: bad escape (end of pattern) at position 14
INFO [2019-10-16 09:08:41,128] cherrypy.error.2410687568264.error.219: [16/Oct/2019:09:08:41] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: identity
  HOST: 127.0.0.1:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 314
`

**Comment by scambra** [comment]
I wrote that code, probably regexp match is not the best way, because I didn't escape special characters (my path had none), and also it may give wrong result if root_mover_path exists in middle of filepath (although it's probably weird). os.path.commonpath or startswith should be better. However I can't test really well with windows path, as I run linux and os.path methods doesn't give same result with backslash.
