### ISSUE TITLE
Watcher changing the status from Snatched to Finished after movie downloaded

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#63]
I recently setup post processing in Watcher to work with nzbget. But for some reason after downloading the movie watcher changes the status from "Snatched" to "finished".  Is there a way to prevent Watcher from changing the status from "snatched" to "finished"?  The reason i ask sometimes watcher gets the wrong movie and instead unchecking "Hide Finished Movies" and going through all movies that are finished, it's much easier to go through the movie's that are tagged as "snatched".  I have downloaded the latest Watcher and still the problem occurs.   Here is a picture what watcher does after it moves the movie and changes the status to "finished".  

![Image Copied on 2019-10-17 at 14 39 10 PM](https://user-images.githubusercontent.com/33842064/67052269-82e04b00-f0f2-11e9-97f7-0cd04dc10bb5.png)

Lastly the logs.

[log.txt](https://github.com/barbequesauce/Watcher3/files/3741512/log.txt)

**Comment by barbequesauce** [comment]
There is not way to prevent the change from snatched to finished. This is not one of the design use cases. 

That said - you could likely write a plugin script to send you a notification on snatch to let you know what was grabbed and what it matched to, so you had an audit trail to review....

**Comment by weekender23** [comment]
thanks for the suggestion.

**Comment by scambra** [comment]
Also, #37 will help you to find that movie when is done.

Another thing you can do is enable scan missing files task, in settings/system, and set to revert status to wanted. Then, when you detect movie is wrong, delete the file, and eventually watcher will automatically set movie back to wanted.

**Comment by weekender23** [comment]
Thank you for the suggestion. I ended up going a back to my old solution.
