### ISSUE TITLE
CSS Changes - Search and Action buttons

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#65]
@barbequesauce @scambra 

Just going through some CSS, and need some input from you both.

I changed the search button to go green on hover, but it affects other things too. I think the search button looks good green on hover, but not so much the others.

Here it is:

![search-hover](https://user-images.githubusercontent.com/16370944/67157419-55c2b100-f31b-11e9-8aa3-9f62dcde2464.png)

btn-secondary is used for other things like the action buttons in the modal boxes.

It currently looks like this: 

![dark-button](https://user-images.githubusercontent.com/16370944/67157424-670bbd80-f31b-11e9-9c73-9a42ddf9b425.png)

But if made green, it would look like this:

![action-1](https://user-images.githubusercontent.com/16370944/67157459-0335c480-f31c-11e9-8040-be386bdbc957.png)

![action-2](https://user-images.githubusercontent.com/16370944/67157461-0cbf2c80-f31c-11e9-8ba7-40c5ea6ddb31.png)

I don't like those buttons green on hover.. so we have these options:

They could go orange like this:

![orange-button](https://user-images.githubusercontent.com/16370944/67157423-607d4600-f31b-11e9-8abe-b3ac2d62737c.png)

Or inverse, like this:

![inverse](https://user-images.githubusercontent.com/16370944/67157575-6a07ad80-f31d-11e9-9bb6-97690e7cb4ca.png)

There's also the 'mild brown' colour that is used as the background:

![mild-background](https://user-images.githubusercontent.com/16370944/67157623-12b60d00-f31e-11e9-9bdf-e7edd2d2a281.png)

Idk if this would blend in too much on the 'found releases' list, as the rows are alternating colours, and one of them is this.

I think my favorites would be either orange or dark:

![dark-button](https://user-images.githubusercontent.com/16370944/67157633-35482600-f31e-11e9-926d-3e5e87655f2e.png)
![orange-button](https://user-images.githubusercontent.com/16370944/67157634-35482600-f31e-11e9-845f-a6b2fc7df39f.png)

Dark is how it is at the moment, but because the search box is white it gives the illusion of the search button shrinking ever so slightly on hover...

![dark-search](https://user-images.githubusercontent.com/16370944/67159239-9cbba100-f331-11e9-804d-647bc5da2058.png)

The dark button 'seems' to be a couple of pixels smaller than the ivory search box (hence this endeavor).

There is another option: leave all the btn-secondary's as dark on hover (like they are now) but change the btn class the search box uses. It could then be green, orange etc without affecting anything else....

What do you think? :)

**Comment by scambra** [comment]
No need to add another class, you can use #search_button selector to set different hover colour.

For other buttons, I like inverse. Orange is good too, although it's used in buttons with orange text, so it's inverting on hover for them.

**Comment by barbequesauce** [comment]
Green for search definitely.

I could go either way on the orange vs inverse question. There’s no “visual grammar” in play that I can see...

**Comment by ellnic** [comment]
Ok, so green for search and inverse for the others. 

Should the search be only green on hover? Or green all the time, with a darkening on hover like button_success?

@scambra I am a complete CSS novice, so I am not sure what you mean by search_button selector. I was just going to change this:

`<button id="search_button" class="btn btn-secondary" onclick="search(event, this)">`

to this:

`<button id="search_button" class="btn btn-search" onclick="search(event, this)">`

then create custom colours for that class. I will change the colours for btn-secondary to inverse on hover.

**Comment by barbequesauce** [comment]
Green on hover is my vote...

**Comment by scambra** [comment]
Green on hover too.

I mean you don't need to change anything in html. Just define CSS with #search_button:hover, instead of changing .btn:hover or .btn-secondary:hover, or adding new class btn-search:

```css
#search_button:hover {
 background-color: ...
}
```

#search_button:hover is a css selector which uses id attribute instead of class

**Comment by ellnic** [comment]
@scambra Where would I define that? In Default.css or add_movie.css? When I said I was a CSS novice, I mean real novice. I've just been change hex codes mostly. I already changed the HTML and added the btn-search class, before I saw your reply. Is this an acceptable way of doing things? Or should I change it back?

**Comment by ellnic** [comment]
This is probably because of the way I [should not] have changed it, but after clicking the search button there is a border left around it, is this a browser thing or would it be solved with the method you mention above?

![search](https://user-images.githubusercontent.com/16370944/67223726-50e72580-f41f-11e9-9fef-f6dda40167dd.png)

**Comment by ellnic** [comment]
Got it, it was the button shadow colour: rgba(76,175,80,0.5). I duplicated the success button, so changing to this: rgba(54,57,66,0.5) in theory should fix. So this was because I created another button class. Now I know... ;)

**Comment by ellnic** [comment]
@scambra I've checked again and I cannot see where to add #search_button. I've got the same result for now using btn-search class - I will make sure I brush up on my CSS, and when I know a bit more about it I will tidy it up using the method you suggested. Thanks for the pointers. :+1:
