### ISSUE TITLE
Question About moving Movies that are split Into 2 files?

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#67]
Is there a way for Watcher to move movies that are split into two files?  For example I downloaded a movie called movieTitle and the movie was split into two files movieTitle.cd1.avi and movieTitle.cd2.avi.  When Watcher was finished downloading the movie it only moved one file and not the other.  I tried adding avi extension in Settings->Postprocessing->Move Additional File Type, but if there is a sample file it moves that with one part of the movie (usually CD2).  Maybe I have overlooked something in the settings.

thanks.

**Comment by barbequesauce** [comment]
The post-processor is currently written to look for the largest file in the directory and PP that. There doesnt seem to be any code allowing for multiple files.

**Comment by scambra** [comment]
Probably best way it's check filename for picked file (largets one), if it has cd1 or cd2 (or check with cd[1-9] regex, although I don't think there will be more than 2), then look for other movie files matching cd[1-9] and same extension and move them too, cdX should be added to filename, at the end or after year.

I never download movies splitted in different files, can you provide the torrent you downloaded as example or others?

**Comment by weekender23** [comment]
I use usenet.  i'll try to find that movie on a torrent site.

**Comment by scambra** [comment]
Can I see the filenames in a website? Or just post them here, if you have other examples post them too.

**Comment by weekender23** [comment]
> Can I see the filenames in a website? Or just post them here, if you have other examples post them too.

Romeo.And.Juliet.1996.iNTERNAL.DVDRip.XviD-MULTiPLY
https://abnzb.com/details/4fb564784e798562ac8e411da07deb43

Rise.Of.The.Footsoldier.LiMiTED.DVDRip.XviD-DoNE
https://abnzb.com/details/c76ccda6c429b3a57736afdd4f73b253

if you have trouble registering to the website, I can take a picture of the file names for you if that helps.

**Comment by scambra** [comment]
Files names for romeo and juliet are multiply-randj-cd1.avi and multiply-randj-cd2.avi
For Rise of the Footsoldier, I don't see multiple video files, there is one big avi, 2 par2 files, nfo file and sample video file.

**Comment by weekender23** [comment]
im sorry i copied the wrong link for Rise of the Footsoldier. Here is the right link:

Rise.Of.The.Footsoldier.LiMiTED.DVDRip.XviD-DoNE
https://abnzb.com/details/6cd26e2b7c729e014cd81730eb1fa876

**Comment by scambra** [comment]
Files for rise of the footsoldier are:
Rise.Of.The.Footsoldier.LiMiTED.DVDRip.XviD-DoNE.1.avi
Rise.Of.The.Footsoldier.LiMiTED.DVDRip.XviD-DoNE.2.avi

Regexp could be "(\bcd ?[1-9]\b.*|\.1)\.<extension>", so only files with same extension as biggest file would be matched, they should end with .1.ext, .2.ext, ..., or have cd1, cd2, ... Also "cd 1" would be accepted. And it should be case insensitive so CD1 and CD 1 are accepted too.
