### ISSUE TITLE
Detect stalled torrents

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#68]
When a torrent is stalled in transmission, and hash matches a snatched search result, watcher should delete it, mark search result as bad, and snatch next best torrent.

A task should check current torrents from transmission, with torrent-get method, and get isStalled (boolean), and activityDate (latest activity) properties. If torrent is stalled, and latest activity is old (it could be a setting), it will be deleted.

**Comment by scambra** [comment]
Torrent could be deleted when isStalled is true and percentDone is not 1. If we add setting to wait until torrent is stalled for X hours, we could save secondsDownloading and current time if secondsDownloading has changed, because activityDate may change if torrent is uploaded.

**Comment by scambra** [comment]
I have a task running every hour to log progress of torrents, and got a stalled torrent.
At 23:24 task reported status downloading, but last activity was at 23:08.
At 00:24 activityDate and downloadedEver didn't change, because torrent is not being seeded, but status was already stalled.

However, I have another torrent whose status is still downloading, but it didn't download anything for 2 hours, although it's seeding.

I have find this about stalled in transmission doc:
queue-stalled-enabled: Boolean (default = true) When true, torrents that have not shared data for queue-stalled-minutes are treated as 'stalled' and are not counted against the queue-download-size and seed-queue-size limits.

Maybe isStalled is not good to check, because probably is only true when torrent doesn't download and upload for 30 minutes. We may want to monitor downloadedEver, for torrents in downloading status, and delete them if no progress for X hours.

**Comment by barbequesauce** [comment]
Makes sense - but the X hours should probably be configurable. I have one site that I get a few MB out of every week or two, the file is coming very slowly due to the few seeders being throttled and often offline. I wouldnt want this killed as it's the only source out there, best I can tell...

**Comment by scambra** [comment]
Good point. X hours would be configurable in downloader setting, but it wouldn't be enough for your case. Task will remove torrent only if status is snatched in database, then it should add another torrent, so it could check if another torrent is available, and don't remove it if it's the only torrent available, other torrents marked as bad wouldn't count.

**Comment by scambra** [comment]
I have added support for detect stalled torrents, but cancel torrent, mark as bad and grab best release are commented, it adds info to log only so you can test it.

If no best release is found, torrent won't be cancelled.

**Comment by barbequesauce** [comment]
Seems to work as advertised - I had a few cancelled/marked bad and next best added...

Nice work!

**Comment by scambra** [comment]
Ok, and did it keep your slow torrent? I will enable real action, not only logging.

**Comment by barbequesauce** [comment]
Yep didn’t touch it. Nice work!
