### ISSUE TITLE
ReScan Library Files

### ISSUE THREAD

**Issue by BS3DP** [barbequesauce/Watcher3#73]
Just been integrating Watcher over my Couch potato install and love it so far but when downloading and testing some things, some downloads finished but the post processing script didn't run correctly (was sorting out some permission issues) So i had to post process my self which is fine but now there's a issue where i cant get Watcher to pick up on the downloaded files in the library folder unless i delete them from the Watcher library and re-scan all my library files to re-add them.

Adding some sort of scan button on the movie in the library to only search for it self in the folder would be a great addition. Maybe something similar to Radarr?

Or i could be doing something wrong, I'm not sure....

**Comment by barbequesauce** [comment]
I think you're looking for the Missing Files Scan. It should identify the files being present and mark the movie as completed.

Go to the Settings menu and select System. Scroll down the page to the Task Scheduler section and find the line that says Missing Files Scan; click the play button on the right side to kick it off...

**Comment by BS3DP** [comment]
As yes like i though, I'm blind, I'm sure i probably looked right at it and didn't notice......
