### ISSUE TITLE
Keep rejected releases with reject reason

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#74]
Rejected releases could be saved, and hidden by default, so current behaviour doesn't change, but users can check them and manually download them if they want. It shouldn't affect to auto grab, rejected releases should never be downloaded automatically, as it happens now.

When rejected releases are listed, reject reason should be displayed. It would help to know if no torrent exist, or all of them were rejected. Also, it would help to adjust size for sources in quality settings, because users would be able to see how many releases were rejected, or detect bugs parsing source or resolution.

**Comment by barbequesauce** [comment]
Great idea - are you thinking a “show rejected “ toggle in the movie pop up? Or a discrete pop up?

**Comment by scambra** [comment]
I'm not sure yet, probably discrete pop up is easier to check, so they are not mixed with accepted releases, or after them.

**Comment by scambra** [comment]
Or maybe, toggle releases listing between accepted and rejected, I think it's better, I don't really like open a new popup, but I want to keep 2 lists.

**Comment by scambra** [comment]
I have added a button next to search button, to toggle between rejected and accepted results

**Comment by scambra** [comment]
I have added a button next to search button, to toggle between rejected and accepted results
@barbequesauce @ellnic what do you think? do you think there is a better place or icon?

**Comment by ellnic** [comment]
I like it there. Nice job :)

**Comment by barbequesauce** [comment]
Looks and works great, nice work!
