### ISSUE TITLE
Add more settings to other torrent clients

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#75]
Some settings added to transmission, such as seed ratio and idle limits, remove finished torrents or detect stalled torrents, could be supported by Deluge too, at least I saw medusa have some of them both in transmission and deluge.

However, someone using another torrent client has to test them, as we are using transmission. I will  research how to implement them for other clients, if someone is going to test it.

**Comment by ellnic** [comment]
I am using deluge. I will test over the next few days.

**Comment by scambra** [comment]
First, I will look for some api docs, to find out how to pass the settings, and what info provides for torrents, and then I will add the settings. I just wanted to have someone ready to test it, before I started to work on it.

**Comment by scambra** [comment]
I have never used deluge, but I can see deluge daemon and deluge webui options in watcher, and 2 downloader modules in watcher, DelugeRPC and DelugeWeb. Can you test both or only one?

**Comment by scambra** [comment]
I have checked torrent settings, to start adding something like seedIdleLimit and seedRatioLimit settings in transmission. I think deluge doesn't have something like stop seeding after some time idle, only stop seeding at ratio, and I saw remove_at_ratio setting, can you confirm?

**Comment by scambra** [comment]
@ellnic I have added 2 options to both deluge modules, it should only set settings when torrents are added, so Torrents Status Check task shouldn't be scheduled, you can check it in settings > system

**Comment by ellnic** [comment]
Got it, thanks :) 

You are right, Deluge doesn't have a stop seeding at Idle unfortunately. 

I am currently using the WebUI option, I can test this first then switch to Daemon later if it doesn't cause any headaches.

**Comment by scambra** [comment]
@ellnic could you test adding torrent with these changes? It would be good if you can test:

* adding torrent with default settings (no ratio, remove finished torrents disabled), it should work as before
* adding torrent with ratio limit set, check if ratio is set for torrent
* adding torrent with ratio limit set and remove finished torrents enabled, check ratio and remove at ratio settings in torrent
* check in settings > system that torrents status check task is not scheduled when remove finished torrents is enabled

Check both with deluge web and deluge daemon, it shouldn't cause any headaches, it's just different way to connect.

**Comment by ellnic** [comment]
Yes, sorry for the delay in this. I’ve only just merged changes into my repo last night so will start testing this evening when I am home. Work hours are pretty mad at the moment so I tend to end up having time later at night. I will report back ASAP.

**Comment by ellnic** [comment]
Ok, so a bit of a problem here. It looks like Deluge has not been functioning as expected. I hadn't really noticed, because most of my requests go via sabnzbd (and deluge tends to be for Sickgear). 

I have:

`LimeTorrents
Rarbg
ThePirateBay
TorrentDownloads
Torrentz2
YTS
Zooqle (backlog only) ` 

selected, and have disabled nzb for these tests.

When I search for something I _know_ exists on say TPB ie. Disney Hercules (1997) I do not get results from anything but zooqle and rarbg. This is a separate issue though.

1. I decided to start with the daemon even though I normally use the WebUI option, but I could not get it to connect:

Watcher logs:

`INFO [2019-11-23 21:17:27,714] core.ajax.get_log_text.569: Dumping log file log.txt to text.
socket.timeout: The read operation timed out
v = self._sslobj.read(len)
File "/usr/lib/python3.6/ssl.py", line 633, in read
return self._sslobj.read(len, buffer)
File "/usr/lib/python3.6/ssl.py", line 874, in read
return self.read(buflen)
File "/usr/lib/python3.6/ssl.py", line 997, in recv
d = self._socket.recv(READ_SIZE)
File "/opt/watcher3/lib/deluge_client/client.py", line 92, in call
result = self.call('daemon.login', self.username, self.password)
File "/opt/watcher3/lib/deluge_client/client.py", line 61, in connect
error = client.connect()
File "/opt/watcher3/core/downloaders/DelugeRPC.py", line 32, in test_connection
Traceback (most recent call last):
ERROR [2019-11-23 21:17:23,786] core.downloaders.DelugeRPC.test_connection.36: Unable to connect to Deluge RPC.
INFO [2019-11-23 21:17:03,756] core.downloaders.DelugeRPC.test_connection.23: Testing connection to DelugeRPC`


2. So I switched back to the Web UI connection, so for now I can report on that:

a. adding torrent with default settings (no ratio, remove finished torrents disabled), it should work as before = YES

b. adding torrent with ratio limit set, check if ratio is set for torrent = YES ( I set 2.3 it was correctly applied)

c. adding torrent with ratio limit set and remove finished torrents enabled, check ratio and remove at ratio settings in torrent = YES (I set ratio 0.1 and the checkbox to remove was checked)

d. check in settings > system that torrents status check task is not scheduled when remove finished torrents is enabled = YES (note: It didn't seem to be enabled with remove finished checked or unchecked).

So for now I would say that what you've done is working very well. :)

**Comment by scambra** [comment]
Ok, I will work on stalled torrents next, but I need to find what info is returned from deluge so we can track when torrent is not downloading.

About Deluge daemon issue, it's a separate issue because test connection is not workig. Is it running on same host as webui? Is it reachable from watcher's docker instance?

**Comment by ellnic** [comment]
Sure, let me know what I need to give you for stalled torrents and I will get on it. Deluge logs?

Does the Deluge API allow you to get info from the Status tab? 

Here is some example info from a stalled torrent:

```Downloading 99.96%
Downloading 99.96%

Downloaded:
    1.4 GiB (0.0 KiB)
Uploaded:
    13.0 GiB (2.1 GiB)
Share Ratio:
    9.608
Next Announce:
    18m 37s
Tracker Status:
    Announce OK

Down Speed:
    0.0 KiB/s
Up Speed:
    0.0 KiB/s
ETA:
    ∞
Pieces:
    1384 (1.0 MiB)
Last Transfer:
    3h 58m

Seeds:
    0 (0)
Peers:
    12 (8)
Availability:
    0.999
Auto Managed:
    False
Complete Seen:
    Never

Active Time:
    76d
Seeding Time:
    ∞
Seed Rank:
    0
Date Added:
    30/08/2019 11:44:24
Completed:
```

In particular, I think this: `Last Transfer: 3h 58m` and this `Active Time: 76d` and this `Complete Seen: Never` could be used to decide if the torrent should be marked stale.

About the Daemon issue:

Yes, it's the same container. It has both the Web UI and the Daemon. I access the Daemon from the app on XFCE, and this is all the same host. I have tried the docker IP (172.x.x.x), host IP (192.x.x.x), and 127.0.0.1. For the web UI, it works with the host IP and Docker IP (not 127.0.0.1) so I am testing with 192.x.x.x but have also tried 172.x.x.x. The error thrown is "[Errno 111] Connection refused". Is any particular address prefix required? I have tried scgi:// (I think Medusa needed this?) but it gives "[Errno -2] Name does not resolve". I checked Sickgear's web UI and it doesn't have a Daemon option, but it does have this: "Verify certificate disable if you get "Deluge: Authentication Error" in your log" could this have something similar?

**Comment by ellnic** [comment]
Btw, I may look at jumping from Deluge once we are done. I am open to helping with other clients like qbitorrent if needed :)

**Comment by scambra** [comment]
Probably last transfer is good to use. In transmission I'm using downloadedEver, which is bytes downloaded, so I'm saving that value in searchresults table and timestamp if they have changed from previous saved value, because it doesn't have last transfer, or I didn't find it.

I think transmission doesn't have something like complete seen. I may use both in get_torrents_status, in deluge module, to return stalled status when both last transfer and complete seen are X hours old.

Deluge wouldn't need tracking status by watcher, so this line may need to be changed to elif config.get('removestalledfor') and 'progress' in torrent:
https://github.com/barbequesauce/Watcher3/blob/master/core/scheduler.py#L406
So only downloader modules returning 'progress' key will have progress tracking in watcher.

I still need to check how deluge return status, to check these columns only when torrent is downloading, but not if it's in queue, and column names in api for keys argument in get_torrents_status:
https://deluge.readthedocs.io/en/latest/modules/deluge.core.html#deluge.core.core.Core.get_torrents_status
I don't know if you can get these values, you should query api from terminal, or you may look at params and response for requests in browser with web inspector.

I want our get_torrents_status to return something similar to every supported client, with stalled detection support. So it must return name, hash and status, and progress if tracking in watcher is needed.

Status must be:
* finished (downloading and seeding done, if removing finished torrents must be done by watcher)
* stalled
* downloading (checked when progress tracking is needed)
* other values, it doesn't care which ones.

When tracking is needed, if torrent is waiting in queue it shouldn't return downloading status (transmission returns download pending), so they are not tracked while in queue.

**Comment by scambra** [comment]
About deluge daemon, I may need to install to debug it, because it don't understsand that error, it's hapenning in line self.call('daemon.login', self.username, self.password), after socket connects, so host (I think it must be IP only) and port must be right, but it times out when sending user and password.

**Comment by ellnic** [comment]
Ok np. I have some time tomorrow morning to have a play with the API. I will see what I can find.

**Comment by ellnic** [comment]
I haven't forgotten about this.. I've spent most of the free time I've had today trying to figure out the ssl issue in 44. I will get on this next. Hopefully later tonight. :)

**Comment by ellnic** [comment]
@scambra urk... I've just tried to get the webAPI working but it turns out I am unable to use it because my container python version is 3.8 and the latest supported egg for the webAPI plugin is 3.7. Took me a while to figure that out, had to check the docs.

 So I started to dig around in the web inspector but this is way out of my understanding.

If you are able to give me some commands to issue from the terminal, I can do that - but it might be quicker and easier for you to fire up a docker.

The webAPI was kinda my go to for this one and I can't use it.

**Comment by scambra** [comment]
@ellnic I need info from network tab, when list is refreshed, or torrent info is displayed. Select request in the list, from headers tab I need request url, and query string parameters or form data, and data from response tab too.

**Comment by ellnic** [comment]
Ah! I think I may have what you need. Is this any help?

Downloading:

```
{"result": {"connected": true, "torrents": {"bd41dc7996258c3e4efbd179fa4a42289b7ac4c3": {"distributed_copies": 24.134000778198242, "download_payload_rate": 16850141, "is_auto_managed": true, "max_download_speed": -1, "max_upload_speed": -1, "num_peers": 0, "num_seeds": 24, "progress": 13.614700317382812, "download_location": "/Downloads-Temp/Incomplete", "seeds_peers_ratio": 1.0, "state": "Downloading", "time_added": 1574942345, "total_done": 194329287, "total_peers": -1, "total_seeds": -1, "total_uploaded": 0, "total_wanted": 1427341312, "total_remaining": 1233012025, "tracker_host": "ubuntu.com", "upload_payload_rate": 0, "eta": 73, "queue": 171, "ratio": 0.0, "completed_time": 0, "last_seen_complete": 1574942359, "name": "xubuntu-18.04-desktop-amd64.iso", "time_since_transfer": 0, "label": ""}}, "filters": {"state": [["All", 181], ["Active", 1], ["Allocating", 0], ["Checking", 0], ["Downloading", 172], ["Seeding", 9], ["Paused", 0], ["Error", 0], ["Queued", 0], ["Moving", 0]], "tracker_host": [["", 3], ["All", 181], ["Error", 28], ["arenabg.com", 1], ["coppersurfer.tk", 84], ["desync.com", 1], ["frostii.com", 2], ["frostii.net", 2], ["gotwoot.net", 5], ["leechers-paradise.org", 18], ["nyaatorrents.info", 3], ["openbittorrent.com", 17], ["opentrackr.org", 19], ["pirateparty.gr", 1], ["point-blank.cc", 2], ["rarbg.me", 12], ["rarbg.to", 2], ["scarywater.net", 1], ["tracker.wf", 7], ["ubuntu.com", 1]], "owner": [["", 0], ["localclient", 181]], "label": [["", 5], ["All", 181], ["lidarr", 0], ["sickgear", 176], ["software", 0], ["watcher", 0]]}, "stats": {"max_download": -1.0, "max_upload": -1.0, "max_num_connections": -1, "num_connections": 183, "upload_rate": 0.0, "download_rate": 17792794.0, "download_protocol_rate": 14180.0, "upload_protocol_rate": 28617.0, "dht_nodes": 376, "has_incoming_connections": 1, "free_space": 307591622656, "external_ip": "x.x.x.x"}}, "error": null, "id": 42}
```

Finished (it calls this paused when not removed)

```
{"bd41dc7996258c3e4efbd179fa4a42289b7ac4c3":{"distributed_copies":0,"download_payload_rate":0,"is_auto_managed":true,"max_download_speed":-1,"max_upload_speed":-1,"num_peers":0,"num_seeds":0,"progress":100,"download_location":"/path/to/downloads","seeds_peers_ratio":1,"state":"Paused","time_added":1574942345,"total_done":1427341312,"total_peers":-1,"total_seeds":-1,"total_uploaded":0,"total_wanted":1427341312,"total_remaining":0,"tracker_host":"ubuntu.com","upload_payload_rate":0,"eta":0,"queue":-1,"ratio":0,"completed_time":1574942420,"last_seen_complete":1574942509,"name":"xubuntu-18.04-desktop-amd64.iso","time_since_transfer":431,"label":""}}
```

Seeding (this is a different torrent):

```
{"result": {"state": "Seeding", "active_time": 31452, "seeding_time": 1474, "distributed_copies": 0.0, "download_payload_rate": 0, "is_auto_managed": false, "max_download_speed": -1, "max_upload_speed": -1, "next_announce": 351, "num_peers": 0, "num_seeds": 0, "owner": "localclient", "progress": 100.0, "shared": false, "download_location": "/path/to/files", "seeds_peers_ratio": -1.0, "seed_rank": 333, "time_added": 1574910746, "total_done": 59323310, "total_payload_download": 59323310, "total_payload_upload": 0, "total_peers": 0, "total_seeds": 3, "total_uploaded": 0, "total_wanted": 59323310, "total_remaining": 0, "tracker_host": "coppersurfer.tk", "tracker_status": "Announce OK", "upload_payload_rate": 0, "num_pieces": 906, "piece_length": 65536, "eta": 0, "queue": -1, "ratio": 0.0, "completed_time": 1574940724, "last_seen_complete": 1574940724, "name": "Show.01.mkv", "time_since_transfer": 1474}, "error": null, "id": 608}
```

**Comment by scambra** [comment]
I can see some column names there, I can use last_seen_complete to detect stalled torrents, if last_seen_complete is older than X hours ago, watcher will remove as stalled torrent. I think it's better than watcher is doing with transmission, because it will keep torrent even when it isn't downloading. Or we could have 2 settings for deluge, one for last_seen_complete and another for time_since_transfer.

Also, I can see status is in state column, the one I care is Downloading, so watcher only deletes torrent if state is Downloading and last_seen_complete is older than X hours ago. I guess time_since_transfer is what you see as Last Transfer in UI, however I have checked and it's updated on seeding too, as transmission does for activity time:

```
    def get_time_since_transfer(self):
        """The time since either upload/download from peers"""
```

So we can't use, a torrent could be stalled but seeding. We can delete as stalled only when last sen complete is older than X hours, or we can track download size as watcher does for transmission, with total_payload_download. Also, I found time_since_download in deluge code, although is not in your results (probably web ui is not requesting it), we could use it. So we could have 2 settings, deletes when last seen complete is older than X hours ago, and time_since_download is greater than X hours. What do you think, @barbequesauce @ellnic?

However, we don't want to delete torrents queued to download, but not downloading. At least transmission have this state, because it downloads only few torrents at same time, so a torrent can be started but there are other torrents downloading. Can you get a torrent in that state and send me info? So I can see if state is different, or I must check some other column. I have read code and I think it return 'Queued'.

Watcher doesn't need to care about finished or seeding torrents in deluge, because Deluge can delete finished torrents by itself.

**Comment by ellnic** [comment]
I believe this is what you want :)

`{"662948f49f28ab7f57e741e5189b6776588e9947":{"distributed_copies":0,"download_payload_rate":0,"is_auto_managed":true,"max_download_speed":-1,"max_upload_speed":-1,"num_peers":0,"num_seeds":0,"progress":0,"download_location":"/Downloads-Temp/Incomplete","seeds_peers_ratio":25,"state":"Queued","time_added":1574961907,"total_done":0,"total_peers":10,"total_seeds":250,"total_uploaded":0,"total_wanted":2260500480,"total_remaining":2260500480,"tracker_host":"ubuntu.com","upload_payload_rate":0,"eta":0,"queue":41,"ratio":-1,"completed_time":0,"last_seen_complete":0,"name":"ubuntu-mate-19.10-desktop-amd64.iso","time_since_transfer":-1,"label":""}}`

I agree on the last_seen_complete and time_since_download. This sounds fairly iron clad. I may just end up staying with Deluge, so I can always continue to test so we can tweak if needs be.

**Comment by scambra** [comment]
I have installed deluge daemon to test get_torrents_status, and I got error connecting to daemon. I had to enable remote access with deluge-console, so I guess you had that issue too.

**Comment by scambra** [comment]
Looks like info we need is not available through api, or at least with get_torrents_status:
https://dev.deluge-torrent.org/wiki/archive/Development/UiClient#Theavailablekeysforget_torrent_statusidkeys

Maybe this info is provided by plugins, and I don't know how to get it:
https://forum.deluge-torrent.org/viewtopic.php?t=55122

We may need to use same way to track as transmission, with total_payload_download. Anyway, I have added get_torrents_status to deluge web and daemon. You can run Torrents Status Check to get info added to log, then you can post here log lines for core.downloaders.DelugeWeb.get_torrents_status

**Comment by scambra** [comment]
I have checked their code in git, and last_seen_complete and time_since_download are in master branch, but they are not in 1.3 branch

**Comment by scambra** [comment]
I have added code which uses last_seen_complete and time_since_download when they are available, and total_payload_download in other case (v1). But I haven't added settings to enable stale detection in deluge, so it won't detect any torrent yet.

Anyway I need log lines from deluge web, because I saw deluge daemon is returning byte string so I need to decode to string to compare with other strings, I don't know if deluge web will need too.

**Comment by ellnic** [comment]
Ok, I can look into the deluge web logs for you over the next couple of days. 

Their master seems to be on 2.0.3 which is the version they have available on the landing page of their site. The docker I use contains 2.0.4. I think using The arch based deluge container and docker in general has spoiled me. I didn’t realise Ubuntu and Debian were still on 1.3! Ubuntu does have a PPA though.

**Comment by ellnic** [comment]
I have found the web log file and it's huge. It also looks like it's truncated after about 4 days because it's so large. Left me know what info you need in the log and I will delete the log and perform the actions.

**Comment by scambra** [comment]
I don't want deluge web log, I want log lines I added to watcher, I got info running Torrents Status Check task with deluge daemon, so I need you run Torrents Status Check from systems page, and post log from watcher, so I can check how response from deluge web is, if it's same as deluge daemon, or has some difference. I care about lines with core.downloaders.DelugeWeb.get_torrents_status, or any error.

For DelugeRPC I get this:
```
INFO [2019-11-29 22:46:06,665] core.downloaders.DelugeRPC.get_torrents_status.187: Get torrents from DelugeRPC
INFO [2019-11-29 22:46:13,073] core.downloaders.DelugeRPC.get_torrents_status.203: {b'state': b'Downloading', b'hash': b'59a183734c972071ec3b3961320b91096510ff80', b'name': b'www.TamilRockers.sh - Boogeyman (2005)[720p - BDRip - [Tamil + Telugu + Eng].mkv', b'total_payload_download': 0}
INFO [2019-11-29 22:46:13,075] core.downloaders.DelugeRPC.get_torrents_status.219: {'hash': '59a183734c972071ec3b3961320b91096510ff80', 'status': 'downloading', 'name': 'www.TamilRockers.sh - Boogeyman (2005)[720p - BDRip - [Tamil + Telugu + Eng].mkv'}
INFO [2019-11-29 22:46:13,076] core.downloaders.DelugeRPC.get_torrents_status.203: {b'state': b'Downloading', b'hash': b'3ced530dce123a35dd1e8d83fb515c013ac45d0b', b'name': b'Boogeyman.2005.1080p.BluRay.H264.AAC-RARBG', b'total_payload_download': 479340379}
INFO [2019-11-29 22:46:13,077] core.downloaders.DelugeRPC.get_torrents_status.219: {'hash': '3ced530dce123a35dd1e8d83fb515c013ac45d0b', 'status': 'downloading', 'name': 'Boogeyman.2005.1080p.BluRay.H264.AAC-RARBG'}
```

**Comment by ellnic** [comment]
I don't feel so rough today so I am taking a look at the logs for this. The log is huge and it looks like it's getting the status of torrents from other apps too.

```
ERROR [2019-12-06 15:33:54,222] core.downloaders.DelugeWeb.get_torrents_status.348: Unable to list torrents from DelugeWeb
INFO [2019-12-06 15:33:54,221] core.downloaders.DelugeWeb.get_torrents_status.327: [truncated - a TON of torrents from sickbeard appear here]
INFO [2019-12-06 15:33:53,954] core.downloaders.DelugeWeb._login.231: Logging in to Deluge Web UI.
INFO [2019-12-06 15:33:53,953] core.downloaders.DelugeWeb.get_torrents_status.301: Get torrents from DelugeRPC
INFO [2019-12-06 15:33:53,953] CPTaskScheduler._task.248: == Executing Task: Torrents Status Check Per User Command ==
```

This may be part of the problem with it pulling in information from a lot of other torrents, but I don't think it correctly applies the label 'watcher' to the torrents it sends to Deluge. The label field in Deluge is blank.

**Comment by scambra** [comment]
Is not anything after Unable to list torrents from DelugeWeb line? I don't see the exception info.

Watcher is asking all torrents status, both for transmissino and deluge, but both accept a list of hashes to return info for those torrents only, so I can change it to request info only for torrents in snatched status. For transmission watcher needs to check status for finished torrents too, so probably it should keep asking for all torrents, but I could change deluge to ask for snatched torrents only.

**Comment by ellnic** [comment]
Let me send you the complete log. Do you have access to the watchernzb gmail?

**Comment by scambra** [comment]
No, I don't, but you can upload it to gist.github.com

**Comment by ellnic** [comment]
Done, I think I have created a private Gist then mentioned you. Do the logs contain what you need? I cleared the logs then triggered the manual status check. The output is what you see there.

**Comment by scambra** [comment]
I have added filter to request only hashes for snatched search results, so output should be shorter. Also, delugeweb returned different json, deluge daemon return a dict, with torrent hash as key and torrent info hash as value, and I think deluge web return a hash with that dict as value for result key. Let me know if you get better output now, you should get a line per download from watcher, with hash, status and name

**Comment by ellnic** [comment]
I have updated the gist. The output is much better (shorter) but I don't see any lines that correspond to any current downloads.

**Comment by scambra** [comment]
I'm trying to get items with this code: response.get('result', {}).items()
It would expect a json such as:
{
  result: {
    'hash': {name: '...', ...},
    'another_hash': {name: '...', ...}
  }
}

Maybe response is different than I thought, I didn't find doc about response format for deluge web.
I have added debug line with keys in response json, and another line with whole json response.

**Comment by ellnic** [comment]
This is what I see now. There is definitely a torrent that has come from watcher, but I see no mention of it in the logs :(


```
INFO [2019-12-13 10:32:46,499] core.ajax.manual_task_execute.1411: Manually executing task Torrents Status Check.
INFO [2019-12-13 10:32:46,499] CPTaskScheduler._task.248: == Executing Task: Torrents Status Check Per User Command ==
DEBUG [2019-12-13 10:32:46,500] core.sqldb.execute.166: Executing SQL command: ['SELECT DISTINCT downloadid, download_progress, download_time FROM SEARCHRESULTS WHERE status = ? AND downloadid IS NOT NULL AND download_client = ?', 'Snatched', 'DelugeWeb']
INFO [2019-12-13 10:32:46,508] core.downloaders.DelugeWeb.get_torrents_status.301: Get torrents from DelugeRPC
DEBUG [2019-12-13 10:32:46,535] core.downloaders.DelugeWeb.get_torrents_status.326: Response keys: ['result', 'error', 'id']
DEBUG [2019-12-13 10:32:46,536] core.downloaders.DelugeWeb.get_torrents_status.327: {'result': {}, 'error': None, 'id': 6}
DEBUG [2019-12-13 10:32:46,536] core.sqldb.row_exists.655: Checking if name="Torrents Status Check" exists in database table TASKS
DEBUG [2019-12-13 10:32:46,536] core.sqldb.execute.166: Executing SQL command: ['SELECT 1 FROM TASKS WHERE name="Torrents Status Check"']
DEBUG [2019-12-13 10:32:46,538] core.sqldb.update.250: Updating last_execution to 2019-12-13 10:32:46 for rows that match name:Torrents Status Check in TASKS.
DEBUG [2019-12-13 10:32:46,538] core.sqldb.execute.166: Executing SQL command: ['UPDATE TASKS SET last_execution=? WHERE name=?', ('2019-12-13 10:32:46', 'Torrents Status Check')]
INFO [2019-12-13 10:32:46,591] CPTaskScheduler._task.273: == Finished Task: Torrents Status Check ==
```

**Comment by scambra** [comment]
I have added debug to display hashes requested to deluge. However, I'm thinking watcher is not finding hash for that torrent, can you open database with sqlite and post result of this queries?

SELECT DISTINCT downloadid, download_progress, download_time FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL AND download_client = 'DelugeWeb'
SELECT DISTINCT downloadid, download_client FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL

**Comment by ellnic** [comment]
Am I doing this right?

```
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> SELECT DISTINCT downloadid, download_progress, download_time FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL AND download_client = 'DelugeWeb'
   ...> SELECT DISTINCT downloadid, download_client FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL
   ...> 
```

No results?

**Comment by scambra** [comment]
Sorry, semicolon was missing at the end of each line

**Comment by ellnic** [comment]
Ok - got it, but it doesn't seem to be fetching anything relevant. I made sure there was a Watcher torrent in Deluge before checking (same as before) and I get this now:

```
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> SELECT DISTINCT downloadid, download_progress, download_time FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL AND download_client = 'DelugeWeb';
sqlite> SELECT DISTINCT downloadid, download_client FROM SEARCHRESULTS WHERE status = 'Snatched' AND downloadid IS NOT NULL;
SABnzbd_nzo_jOdQpj|Sabnzbd
SABnzbd_nzo_1n4l3X|Sabnzbd
SABnzbd_nzo_i8tw9e|Sabnzbd
SABnzbd_nzo__oFlkB|Sabnzbd
sqlite> 
```

It shouldn't be returning Sabnzbd results....
