### ISSUE TITLE
CSS themes - what next?

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#82]
@barbequesauce @scambra 

Over the next few weeks I plan to start working on the other themes. 

Here are my thoughts on each:

1. Light - should be the next worked on so we have a light and dark option. Should be easy to sort with minimal effort. 

2. Midnight - works well with the new branding

3. Slate - so close to the default that it’s not really needed, although it is different and would be really easy to sort... copy/paste the majority of stuff as it would work and not clash

4. Spruce - I really don’t like this. I wouldn’t lose sleep if it got removed. I suppose leaving user choice is always a good thing and very little ongoing CSS maintenance would be needed once it is sorted... but, I still don’t like it. 

We could:

a. Remove it
b. Adjust to a ‘more acceptable’ shade of green - if so, what?
c. Replace it with an orangey theme called ‘Amber’? Idk. 

What are your opinions?

**Comment by barbequesauce** [comment]
I like option b... plus add amber 🤣

**Comment by scambra** [comment]
I don't like colours for most of themes, but I think we can keep it, I don't think there is too much to maintain in themes. Maybe option b could make it better.

**Comment by ellnic** [comment]
Got it. So I will do in this order:

1. Light
2. Slate (easy and quick)
3. Midnight
4. Spruce
5. Amber

I am not keen on the colours either, but agree they should be maintained for user choice.

**Comment by ellnic** [comment]
There's still a LOT to do, but this is how it's shaping up so far.

The default was quite heavily modified, things like border-radius on everything that isn't present in the Light theme (and probably the others). If I had known this, I would have modified a copy of the default to make it light... it would have been much quicker. This is making me question how worthwhile it will be to do all of them! Time vs Reward wise.

Anyway, some screenshots:

![Screenshot 2019-11-29 at 20 14 08](https://user-images.githubusercontent.com/16370944/69890568-6721b480-12ee-11ea-9b03-733eb5c4e656.jpg)
![Screenshot 2019-11-29 at 20 33 22](https://user-images.githubusercontent.com/16370944/69890569-6721b480-12ee-11ea-9f3a-976923987ae0.jpg)
![Screenshot 2019-11-29 at 20 34 38](https://user-images.githubusercontent.com/16370944/69890570-6721b480-12ee-11ea-8663-f3330427cae5.jpg)
![Screenshot 2019-11-29 at 20 34 55](https://user-images.githubusercontent.com/16370944/69890571-6721b480-12ee-11ea-9fd2-a24ad256f67b.jpg)
![Screenshot 2019-11-29 at 20 49 25](https://user-images.githubusercontent.com/16370944/69890572-67ba4b00-12ee-11ea-9cae-da7412816086.jpg)

Feel free to criticise @barbequesauce @scambra (and anyone else lurking!), it's far from finished. The yellow sucked a lot on the pale backgrounds so it's gone blue. I actually quite like :)

**Comment by barbequesauce** [comment]
Looks great!

**Comment by ellnic** [comment]
I think I'm done.. I've taken out a lot of the white and silver/grey. I think probably some more can come out at some point, but not right now. It's functional :)

![Screenshot 2019-11-30 at 14 57 32](https://user-images.githubusercontent.com/16370944/69902185-6aff1680-1382-11ea-818f-4a8926b31a17.jpg)
![Screenshot 2019-11-30 at 14 57 42](https://user-images.githubusercontent.com/16370944/69902186-6aff1680-1382-11ea-982d-dedf01fbf643.jpg)
![Screenshot 2019-11-30 at 14 58 20](https://user-images.githubusercontent.com/16370944/69902187-6aff1680-1382-11ea-8642-0a6ab6c584f0.jpg)
![Screenshot 2019-11-30 at 14 58 34](https://user-images.githubusercontent.com/16370944/69902188-6aff1680-1382-11ea-8024-2531d7a942db.jpg)
![Screenshot 2019-11-30 at 14 58 59](https://user-images.githubusercontent.com/16370944/69902189-6b97ad00-1382-11ea-9ecd-d368f9a300c1.jpg)
![Screenshot 2019-11-30 at 14 59 22](https://user-images.githubusercontent.com/16370944/69902190-6b97ad00-1382-11ea-98d2-473ba564d4bd.jpg)
![Screenshot 2019-11-30 at 15 03 13](https://user-images.githubusercontent.com/16370944/69902216-badddd80-1382-11ea-8f66-52b454ec1641.jpg)
![Screenshot 2019-11-30 at 15 03 44](https://user-images.githubusercontent.com/16370944/69902218-badddd80-1382-11ea-8372-80e79c03b78e.jpg)
![Screenshot 2019-11-30 at 15 03 59](https://user-images.githubusercontent.com/16370944/69902219-badddd80-1382-11ea-9e4b-6f27f212687f.jpg)

**Comment by ellnic** [comment]
https://github.com/barbequesauce/Watcher3/pull/86

**Comment by scambra** [comment]
Everything looks great! Maybe some CSS rules could be shared by all themes, so there is no need to make same changes in all theme files. I don't know how much work is, maybe is less work than fix all other themes

**Comment by ellnic** [comment]
That would be cool, wouldn’t know where to begin though. I’m literally running through the css files in an app called Espresso (very cool btw) then adjusting hex codes.

**Comment by ellnic** [comment]
I have just finished the [very minor] lot of modifications to the Slate theme. It's pretty much the same as the default, but 'blacker blacks' and 'whiter whites'. It /is/ different, but I personally think the default wins any day. Choice being the name of the game though, it's there and available.

![Screenshot 2019-12-08 at 20 30 54](https://user-images.githubusercontent.com/16370944/70395771-2581bf80-19fa-11ea-9330-fa0f3cdd2d15.jpg)
![Screenshot 2019-12-08 at 20 31 15](https://user-images.githubusercontent.com/16370944/70395772-2581bf80-19fa-11ea-9bb3-4ec9770f6fad.jpg)

Changes merged into my branch for you to merge into master at your convenience @barbequesauce

**Comment by barbequesauce** [comment]
Done and dusted, thanks @ellnic
