### ISSUE TITLE
Plugin folder for docker

### ISSUE THREAD

**Issue by deepika05** [barbequesauce/Watcher3#83]
shouldnt the plugin folder be also moved to the /config folder or atleast made available to be outside the container during the container setup?

**Comment by deepika05** [comment]
i found that i can manually create "plugin" folder inside "config" from looking at the watcher launch command..

**Comment by ellnic** [comment]
Thanks for bringing this to my attention. I have altered my docker which is where most the changes for just the docker happen. Changes will be merged soon.
