### ISSUE TITLE
We need to talk about site links :)

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#88]
![site_links](https://user-images.githubusercontent.com/16370944/69906497-5770a180-13bc-11ea-8e5d-f0b4c5ee40a5.png)

I know it's a small thing, but I am on a visual appearance mission at the moment. 

1. We aren't really using reddit. The question is: ditch the link or create a r/watcher3? As much as I love reddit, I tend to read more than post - and it's going to end up being a support forum. We have git for that kind of thing.

2. Git, obviously can stay

3. Docker instead of reddit?

Thoughts? @barbequesauce @scambra

**Comment by barbequesauce** [comment]
I’m onboard with #3. Reddit just frustrates me.

**Comment by scambra** [comment]
I don't use reddit, if linking reddit means we should check and answer there, I'm with #3 too.

**Comment by ellnic** [comment]
We’ve all gone down with a nasty virus so I am going to be limited over the next few days :-( 

On the upside, I’ve completed this. I had to update the Material Icons as the originals were v2 and didn’t have docker. The new set is v4.6.95 from Templarian. There was also some missing scss stuff (probably wasn’t required 2 years ago) and some other files with name to code lookups that needed updating. The new set didn’t have an svg font, so I removed the old one. It doesn’t seem to be required though, and all mdi icons are displaying. 

That was a lot more difficult half conscious and on an iPhone at 5am than I would have liked, but: a win is a win :-)

![08C2C16A-7E5D-471C-97BD-7D4ECC9E5F70](https://user-images.githubusercontent.com/16370944/70000204-6ee19300-1552-11ea-88a4-b88f93c65bc8.jpeg)

I’ve created a PR but it’s a mess. Seems to drag a ton of other stuff in which has already been merged anyway. This is making my head hurt. 😬 #89

**Comment by ellnic** [comment]
Ok sorted, totally my fault for PRing to master and not my branch #92

**Comment by ellnic** [comment]
Since Codacy was bitching a lot about some of the CSS, I have ending up close #92 and changing it AGAIN. In #94 I have also removed all the !important tags in all themes. I do not think they are needed for a propertly formatted CSS file - and specific !importants can be re-added if needs be.

**Comment by barbequesauce** [comment]
You're wrapped up here, right?

**Comment by ellnic** [comment]
Yes sorry I will close. I’ve hardly touched my laptop over the last few days as I’m still down with this b**** of a virus.
