### ISSUE TITLE
Feature Request: Separate "Found" from "Waiting"

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#9]
When there's a ton of movies in your "waiting" queue, it's sometimes tough to see when one's converted to "Found".

I'm new to Watcher, but I _think_ it should auto-downloaded when a movie matches your quality profile, so "Found" shouldn't matter. But so far, that doesn't seem to happen for me. So separating "Found" into its own section would be helpful to easily see movies that have torrents that you can send to your downloader.

**Comment by jandreaucodes** [comment]
While I'm requesting stuff "Snatched" being separate would be nice. Since I have it set to look for a better quality torrent for 7 days, I _think_ things that are done are staying in Snatched, so it'd be nice to have a place to look at them all in one fell swoop.

**Comment by barbequesauce** [comment]
For the first point about things being "stuck" in Found - you should check your search and quality settings, especially [Grab Best Release](https://github.com/nosmokingbandit/Watcher3/wiki/Settings-and-Configuration#grab-best-release) and [Wait X Days to Grab](https://github.com/nosmokingbandit/Watcher3/wiki/Settings-and-Configuration#wait--x--days-to-grab).

I'll start working on a option list specific to certain states as you describe.

**Comment by scambra** [comment]
I think it would be good to have a filter to select status to list, so you can list waiting, wanted, found, snatched or finished. And having a status counter when is not filtering by status, such as 3 waiting, 5 wanted, 1 found, 2 snatched.

**Comment by barbequesauce** [comment]
Yep - my current thinking about this is something like SickGear's approach - see the below image.

<img width="592" alt="Screen Shot 2019-10-10 at 5 35 34 PM" src="https://user-images.githubusercontent.com/25070944/66608464-9df80b80-eb84-11e9-98cc-590b23209fda.png">

It's dependent on me fixing the logic breaks I introduced with the per_page dropdown and the conflicts with the logic for hide_finished_movies in status.js, though, which has not been easy.

**Comment by scambra** [comment]
Also, to separate found for waiting you can sort by status.
Hide finished checkbox can be removed with those sickgear-like filters.

**Comment by scambra** [comment]
@barbequesauce have you started to work on status filters? I'm going to work on categories filters and I would like to work on this at same time

**Comment by barbequesauce** [comment]
Only in the sense that I'm looking at the existing code inventorying what has to change - nothing substantial... go for it.

**Comment by scambra** [comment]
fixed by 4ab3712

**Comment by barbequesauce** [comment]
Question on this - when I deselect "finished", nothing happens. If I refresh the screen, it reloads with all other statuses visible in the library view and finished unchecked.

Should the page refresh after the checkboxes are checked/unchecked? Meaning, should the filters apply immediately to the view? Alternately, should there be a submit button to force the refresh?

**Comment by scambra** [comment]
Filters are applied immediately in my browser, library is refreshed by JS. Are you getting any error in console?

**Comment by scambra** [comment]
Ok, I found bug, I broke refreshing library when checkbox status changes when I removed movie_count global variable. I have fixed with 42ec1b6.

**Comment by barbequesauce** [comment]
Amazing work as always, thank you!
@jandreaucodes can you confirm please?

**Comment by jandreaucodes** [comment]
1000% on board with how you guys implemented the new filters.

The page redraws a little weird. It's blank for a second, then shows the movies with the loading gif on top of it. Not the end of the world, but probably not how it was intended to be built.
