### ISSUE TITLE
Discard search results if year doesn't match

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#98]
Some movies have different versions or remakes, and some indexers return movies with same name although year doesn't match, so watcher should check it.

Also, sometimes I found movies have one year in watcher and some torrents have next or previous year, so we may subtract some points if year difference is 1 or 2, and reject if difference is greater. Or add some points when year matches exactly, accept if year is missing or difference is 1 or 2 without extra points, and reject when difference is greater, so torrents with exact year match would be snatched first, it they match top desired quality.

**Comment by barbequesauce** [comment]
There is code in there to fuzzy the year by one or two years already... take a look around [here](https://github.com/barbequesauce/Watcher3/commit/b1e1cc4de444a225f080342c42495a0b8614e36c#diff-a74ad8dfacd4f985eb3977517615ce25)

**Comment by scambra** [comment]
I got results for old movie when looking for dont be afraid of the dark 2010. I got this result:
Don't Be Afraid Of The Dark (1973) [BluRay] [720p] [YTS LT]
http://www.torrentdownloads.me/torrent/1667481375/Don%27t+Be+Afraid+Of+The+Dark+%281973%29+%5BBluRay%5D+%5B720p%5D+%5BYTS+LT%5D

I may need to debug why that code didn't reject that result.

**Comment by scambra** [comment]
I have checked current code, I made changes on that method to use PTN to parse title, because for some movies it rejected incorrectly some search results, if they didn't follow pattern title (year) other info.
https://github.com/barbequesauce/Watcher3/commit/37311e7a04182b35310fa21adc1b76006bbad28d

I think we may add code in that method to add 20 points if year (as extracted by PTN) is exact match, and reject if year is extracted by PTN, and absolute diff with expected year is greater than or equal to 2.

**Comment by barbequesauce** [comment]
works for me.
